### ISSUE TITLE
DAAS Memory dump detector

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#109]
Detector should return data if memory dump was taken by DAAS

**Comment by andreyse** [comment]
let ActiveWorkersInTimeRange = toscalar(StatsDWASWorkerProcessTenMinuteTable
| where TIMESTAMP >= datetime(2017-01-09 01:50:00) and TIMESTAMP <= datetime(2017-01-10 02:00:00) and Tenant =~ "e2d15097c88f4ab688eacc1788470d4f"
| where (ApplicationPool =~ "lsi-irondirect-prod" or ApplicationPool startswith "lsi-irondirect-prod__")
| project TIMESTAMP, RoleInstance
| summarize makeset(RoleInstance));
StatsDWASWorkerProcessTenMinuteTable
| where TIMESTAMP >= datetime(2017-01-09 01:50:00) and TIMESTAMP <= datetime(2017-01-10 02:00:00) and Tenant =~ "e2d15097c88f4ab688eacc1788470d4f" and (ApplicationPool =~ "lsi-irondirect-prod" or ApplicationPool startswith "lsi-irondirect-prod__")
| project TIMESTAMP, ApplicationPool, RoleInstance
| join
(
    AntaresRuntimeWorkerEvents
    | where TIMESTAMP >= datetime(2017-01-09 01:50:00) and TIMESTAMP < datetime(2017-01-10 02:00:00) and Tenant =~ "e2d15097c88f4ab688eacc1788470d4f"
    | where RoleInstance in (ActiveWorkersInTimeRange)
    | where EventId == 62500 and EventMessage contains "Memory dump for process" 
    | project TIMESTAMP = bin(TIMESTAMP, 10m) , ACTUALTIMESTAMP = TIMESTAMP, RoleInstance , EventMessage
)
on TIMESTAMP, RoleInstance
| project TIMESTAMP = ACTUALTIMESTAMP, RoleInstance , EventMessage

**Comment by PraveenTB** [comment]
we can do this later if the importance improves
