### ISSUE TITLE
Too many downtimes to sort thru in AppAnalysis

### ISSUE THREAD

**Issue by lambointx** [ShekharGupta1988/AppLensV2#111]
https://applensv2.azurewebsites.net/sites/gciplatformprod/appanalysis?startTime=2016-11-03

14 separate downtimes (looks like pretty much of their day was a downtime)

The ability to define a user defined  window to use as a downtime would be useful. (Adjusting a window in the graph, or the SLA%)

**Comment by stevenernst131** [comment]
I have made the downtimes expandable to it is a little easier to sort through them however I did not change the logic for how many downtimes are displayed. Will require a backend change. See #131
