### ISSUE TITLE
The timezone info dispalyed in the charts are incorrect. 

### ISSUE THREAD

**Issue by kaushalp** [ShekharGupta1988/AppLensV2#113]
This is seen across multiple charts. In the Frebs Logs Analysis (appanalysis) the X-axis is set  to "**Time (UTC)**". When I hover over the section it picks up the PC timezone. See the below screenshot. 

![image](https://cloud.githubusercontent.com/assets/4186691/20047993/3dad6192-a4df-11e6-821d-f6e2516106a6.png)

The displayed time zone information in the chart is incorrect. All the timestamps are still in UTC.

**Comment by kaushalp** [comment]
I tried it from another machine and here it is displayed correctly. Note the timestamp and the timezone.

![image](https://cloud.githubusercontent.com/assets/4186691/20048061/b8931cb2-a4df-11e6-901c-a0a663847704.png)

**Comment by stevenernst131** [comment]
We are aware of the problem. I investigated last week and it seems like it could be a bug in the charting library, because it only seems to happen on the bar charts
