### ISSUE TITLE
Detector to say that all the requests that were failing were failing on a specific worker

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#114]
This detector would be able to say that a specific worker is at fault for most or all of the failed requests. 

This could be an umbrella detector since it is not really telling the cause. However we could also use this data in the CPU and memory detectors so that the CPU detector is not beeping for a worker that did not have any failed requests.

**Comment by PraveenTB** [comment]
other issue already tracks this
