### ISSUE TITLE
Worker displaying improperly

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#119]
![image](https://cloud.githubusercontent.com/assets/7739017/20115059/abd77ee2-a5ab-11e6-9a99-929dad6db5ff.png)

**Comment by aspaan** [comment]
is it possible to get this site and date, i can not reproduce this

**Comment by stevenernst131** [comment]
I should have included a link originally. I have not seen this happen anymore, so we can close it and if we can get a repro then we can reopen it.
