### ISSUE TITLE
Proper fix for low traffic pattern where there is low average availability and high standard deviation

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#131]
- One change is we consider 100% availability for no data points in our APIs and then run the existing algo. This will take care of low traffic pattern also and wont affect high traffic pattern

- Second change is we need to do 2 pass filter on the traffic to figure out abnormalities. (We discussed this during hackathon if you remember). Right now I am doing 1 pass filter.

**Comment by ShekharGupta1988** [comment]
closing for now. We haven't heard this problem in a while. Will study customer data for Avg number of downtimes we are reporting and then re-visit this later.
