### ISSUE TITLE
Storage Failover output inconsistent

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#133]
[Original App Lens](https://applens.azurewebsites.net/#/jmwebsite-prod/2016-11-11) shows 8 storage failovers

[ApplensV2](https://applensv2.azurewebsites.net/sites/jmwebsite-prod/detectors/storagefailover?startTime=2016-11-11) shows only 3 and also sometimes I refresh the page and I see 2 more File Server Failovers that would match up with the first bunch from the original app lens

**Comment by aspaan** [comment]
Found the bug checkin gin fix
