### ISSUE TITLE
Kusto link for failover does not work

### ISSUE THREAD

**Issue by jsandersrocks** [ShekharGupta1988/AppLensV2#135]
https://applensv2.azurewebsites.net/sites/viawebapp/detectors/storagefailover?startTime=2016-11-07
Hit the kusto link and nothing displays
https://wawseus.kusto.windows.net/wawsprod?query=H4sIAAAAAAAEAHWQwUoDMRCG74Lv8JNTCy1ki9pSukJFD0LV0q3sscTN0I2yyZJMuwjisxv30FZXQ24z3z%2ffzNyy8hRWO8umotz5N%2fJ3e7IccH6Gk%2feBpiRPWHoqTKB17M5YVTWuU2jF9I33RjK5GibJUI4h5bT9fSiru9TsL2ryi8rczhf04KyJVkg%2fIfJ5ni1XT7c3i2d5MRb%2fOLYL3GukKZJLOZq0YQu3jaOZqlhDiFtzaAyXgFiXBO8cQ5uoyc6%2fo1QBRanslrRo6V5mmB5VRa3G3qiGXlRdCziPQ%2bkk9diy2Yh%2bx7P27jWO6txlcAgb%2fBD%2bArZFpBWnAQAA

**Comment by aspaan** [comment]
https://applensv2.azurewebsites.net/sites/viawebapp/detectors/storagefailover?startTime=2017-01-31
I tired the latest failover on the same site and it worked
 were you clicking this directly on Chrome? please copy the link and paste it in IE 
At the moment chrome doesnot support Kusto links
