### ISSUE TITLE
Get the "Custom Domain Add Operations" detector functional again

### ISSUE THREAD

**Issue by nmallick1** [ShekharGupta1988/AppLensV2#1397]
The "Custom Domain Add Operations" detector is no longer working. It is unable to fetch data from Kusto endpoint.

**Comment by nmallick1** [comment]
Looks like we do not have access to the Kusto cluster and instead of throwing an exception we return empty result.

**Comment by puneetg1983** [comment]
I think this is a known issue and our backend should handle this properly. We should not return NULL if there is an exception reaching the KUSTO or the query has an issue.....Might want to check with @stevenernst131 regarding this...

**Comment by nmallick1** [comment]
Thanks Puneet. Steve and I checked this yesterday. AppLens does not have access to the AzPortal cluster and hence the detector isn't working.


However, you are correct. This should be handled appropriately.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by stevenernst131** [comment]
I think i see the problem in the code now. We are not throwing the exception that we are catching. 

```C#
            try
            {
                HttpResponseMessage responseMsg = await _httpClient.SendAsync(request, tokenSource.Token);
                responseContent = await responseMsg.Content.ReadAsStringAsync();

                if (!responseMsg.IsSuccessStatusCode)
                {
                    throw new Exception(responseContent);
                }
                else
                {
                    dataSet = JsonConvert.DeserializeObject<DataTableResponseObjectCollection>(responseContent);
                }
            }
            catch(Exception ex)
            {
                kustoApiException = ex;
                // There should probably be a 'throw;' here
            }
            finally
            {
            ....
```

**Comment by ShekharGupta1988** [comment]
hey folks, I remember there was a throw here as onboarding flow was showing the exceptions. I guess this regressed.

**Comment by ShekharGupta1988** [comment]
It looks like it got regressed with this change:
https://github.com/Azure/Azure-AppServices-Diagnostics/commit/c21b175cc978e2648631ca93a4af55e17d7f2e4b#diff-a44db3fdfacaff855cfce0b03d50ce02

**Comment by stevenernst131** [comment]
I can submit the change. Did not mean to get rid of the throw.

**Comment by stevenernst131** [comment]
Oh looks like there was no try catch before.

**Comment by stevenernst131** [comment]
Addressed in https://github.com/Azure/Azure-AppServices-Diagnostics/pull/100
