### ISSUE TITLE
Account for a sitename that coexist in regular stamp and ministamp

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#143]
When sending a request to Observer GetWebSite API, Observer fails with 500 because it assumes that site names are unique to only one stamp.

**Comment by ShekharGupta1988** [comment]
One more case:
https://applensv2.azurewebsites.net/sites/LuiIntegrationv1-Prod/appanalysis

This is the case where the same site belongs to 2 ASEs:
-  aseprdcc01(waws-prod-sy3-b080b226)
- aseprdcc01(waws-prod-ml1-5604b6e4)

As you see, both the mini stamps also have same name but different internal names.
