### ISSUE TITLE
Worker Availability Detector - need to modify this detector

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#144]
This detector needs to beep only when it can find specific problem - one worker where all the errors are happening.

Also, looks there is some problem in metrics here.
https://applensv2.azurewebsites.net/sites/rethinkfirst/appanalysis?startTime=2016-11-30

Now open its kusto data and chart the Http5xx. You'll see different graph

**Comment by PraveenTB** [comment]
1. If the site runs on more than 1 worker
and 
2. if the failures are coming only from 1 worker we say the following:

Problem: Your site is experiencing availability issues. All issues are happening on one worker only - SmallDedicated_In_23
Solution: 
   1. Try restarting the instance on the faulty worker
   2. Scale to higher tier temporarily and scale it back. This gets you new workers and may solve the issue for now
