### ISSUE TITLE
Feature Suggestion: Detect Performance Issues with Asp.Net Core and dotnet.exe

### ISSUE THREAD

**Issue by FinVamp1** [ShekharGupta1988/AppLensV2#160]
It would be good to have insight to the dotnet.exe performance and statistics if that's the application platform that the customer has chosen. We are seeing a potential trend for performance issues with these types of apps and AppLensv2 would be very useful in knowing where to start. Will let the TA's know about this issue and to add more details to this Issue.

**Comment by ShekharGupta1988** [comment]
Thanks Finbar for reporting. If you can also add some examples/CRIs that you/TA's saw, this would help us scope this ask for first release.

**Comment by puneetg1983** [comment]
Closing this issue as of now as this doesnt have any clear info \ask
