### ISSUE TITLE
Create Feedback for specific detectors

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#161]
This is the long term plan of adding some kind of learning

**Comment by ShekharGupta1988** [comment]
Support Feedback on this (from red zone meeting)

The feedback should include:
- Case number
- Three options:
      - It helped identifying root cause
      - It pointed me to right direction
      - It didn't help
- Things that can be added to improve.


There is a merit in doing analytics on such feedback also (for future improvements and leanings).
