### ISSUE TITLE
Add query to get puid of user who restarted site

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#165]
Hi folks, 
  Ask : Can we also add  queries in  “Data Source” that can provide PUID of the user who restarted the site ? 

At this time, gives me info on the   Applensv2 : https://applensv2.azurewebsites.net/sites/TWLYourWarehouse/detectors/siterestartuserinitiated?startTime=2016-12-05 

 

Here are the steps that I had to take in this case to get to the User who triggered the restart : 

I grab the RequestID from Kusto query for restart eventID 18007 : 

https://wawseas.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
AntaresRuntimeWorkerEvents 
| where (TIMESTAMP >= datetime(2016-12-05T05:45:10Z) and TIMESTAMP < datetime(2016-12-05T18:45:10Z)) 
|  where Tenant == '4f6320c7733746d5b7c9584ce1f02676' 
| order by TIMESTAMP asc
| where ApplicationPool contains"TWLYourWarehouse"or SiteName contains"TWLYourWarehouse" 
| where EventId == 18007
| where RoleInstance==@'MediumDedicatedWebWorkerRole_IN_129'or RoleInstance==@'MediumDedicatedWebWorkerRole_IN_92'or RoleInstance==@'MediumDedicatedWebWorkerRole_IN_120'or RoleInstance==@'MediumDedicatedWebWorkerRole_IN_61'or RoleInstance==@'MediumDedicatedWebWorkerRole_IN_10'
| project EventMessage , RequestId 

 

In this case , the API request ID column has this value : 

RequestID is  : a0941d82-a327-4556-bdf5-91b8295d66c2 

In the HttpIncoming Requests table , this value will be marked as serviceRequestId

https://armprod.kusto.windows.net:443/ARMProd [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
HttpIncomingRequests 
| where (TIMESTAMP >= datetime(2016-12-05T05:45:10Z) and TIMESTAMP < datetime(2016-12-05T18:45:10Z))
| where subscriptionId == "b41d828c-b13e-41e2-8542-1b906bd70c88" 
| where serviceRequestId == "a0941d82-a327-4556-bdf5-91b8295d66c2"  
| project  principalPuid, authorizationAction  , targetUri 

From the portal, the site was triggered a restart and I grabbed the principalPuid
 
 
In this case, this value is  : 1003BFFD8B5C5B46 

I used ACIS to find out who triggered this action :
https://acis.engineering.core.windows.net/WorkFlowHome.aspx?Endpoint=Microsoft&Customer=1003BFFD8B5C5B46 

Here is the email ID of the user who triggered this restart:

**Comment by andreyse** [comment]
We need to whitelist kusto armprod cluster for this request
