### ISSUE TITLE
Instance Allocation Beeping without any actual issue

### ISSUE THREAD

**Issue by aspaan** [ShekharGupta1988/AppLensV2#168]
https://applensv2.azurewebsites.net/sites/mystate/detectors/instanceallocations?startTime=2016-12-06

**Comment by aspaan** [comment]
another example https://applensv2.azurewebsites.net/sites/luiintegrationv1-prod/appanalysis?startTime=2016-12-18

**Comment by stevenernst131** [comment]
@"StatsDWASWorkerProcessTenMinuteTable 
            | where TIMESTAMP >= datetime({StartTime}) and TIMESTAMP <= datetime({EndTime}) and Tenant =~ ""{Tenant}"" 
            | where {SiteName_Filter} 
            | project TIMESTAMP, ApplicationPool, RoleInstance
            | summarize **makelist(RoleInstance)** by bin(TIMESTAMP, 10m)
            | order by TIMESTAMP asc";

should be makeset not makelist, because makeset will not have repeated values. I have a fix.
