### ISSUE TITLE
Detectors that have detected abnormal time periods should have a badge on them

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#17]

**Comment by ShekharGupta1988** [comment]
To Add more info here- the work requires updating Sia model to include list of detectors that beeped not necessarily correlated with downtime.

In UI, when sia repsonse is fetched, use this list of detectors to add a badge of importance in front of detector names in side menu

**Comment by aspaan** [comment]
tested it on prod
its good

**Comment by ShekharGupta1988** [comment]
Why did you close this ?

Thanks
Shekhar

________________________________

**Comment by ShekharGupta1988** [comment]
Oh capi thought that's the one I was supposed to close

**Comment by aspaan** [comment]
ui on left asort by related ranked
then no related and ranked
and then no related and not fired ranked

IN API for SIA also include the un related but fired detectors
