### ISSUE TITLE
Requests dropped detectors has too many downtimes

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#178]
![image](https://cloud.githubusercontent.com/assets/7739017/21129539/efad66f6-c0b6-11e6-90ef-e76d762f5825.png)

Looks like it is just creating a downtime period for every time there any difference between the count on the front end and on the worker.

1. They aren't being merged which really wouldn't solve the problem because the entire thing would be one big downtime 
2. May have to do actually find when there are more than normal similar to how we look at traffic. 

This detector will only show up for private environments that have been updated this week with new code. 

path: /sites/autocosmosroadtrip/detectors/requestsdropped?startTime=2016-12-05T12:00:00 (I was on localhost when I ran into this)

**Comment by ShekharGupta1988** [comment]
This I think is fixed with recent deployment.
Closing the issue
