### ISSUE TITLE
ASE: Canary Site name is null

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#182]
The current query we have to fetch canary site name somehow is not working for ASE Site.

**Comment by ShekharGupta1988** [comment]
https://applensv2.azurewebsites.net/sites/luiintegrationv1-prod

**Comment by ShekharGupta1988** [comment]
One suggestion - you can use observer call to get canary hostname.

**Comment by stevenernst131** [comment]
Per ASE conversation:

Ben: "The runners for ASEs are currently stopped and if the ASEs are ACLed they do not work. The results are saved to a different set of tables."

Petr: "Yes, the plan is to make canaries work for ASEs as we need that to work also for full support in RHC."
