### ISSUE TITLE
ASE: CPU Detector showing percentage more than 100%

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#183]
example - 
sites/luiintegrationv1-prod/detectors/cpuanalysis?startTime=2016-12-13T00:58:46.328Z

**Comment by stevenernst131** [comment]
I am already getting the RD instance name from the role heartbeat table and that table also has core count. 

Before:
![image](https://cloud.githubusercontent.com/assets/7739017/21245450/5395d668-c2d7-11e6-89b2-8fb456c728eb.png)

After:
![image](https://cloud.githubusercontent.com/assets/7739017/21245467/6adae408-c2d7-11e6-9827-413072c17ba1.png)
