### ISSUE TITLE
ASE: Memory Analysis is showing negative percentage

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#184]
Example-
sites/luiintegrationv1-prod/detectors/memoryanalysis?startTime=2016-12-13T00:59:55.239Z

**Comment by stevenernst131** [comment]
I am already getting the RD instance name from the role heartbeat table and that table also has core count. I make an assumption that physical memory size is core count * 1.75GB:

![image](https://cloud.githubusercontent.com/assets/7739017/21245352/ce290c70-c2d6-11e6-9d99-37d787b7d5f5.png)


Before:
![image](https://cloud.githubusercontent.com/assets/7739017/21245256/6a977c96-c2d6-11e6-979b-8960e4e40769.png)

After:
![image](https://cloud.githubusercontent.com/assets/7739017/21245290/8fabeba2-c2d6-11e6-869a-4a82f1705dcc.png)
