### ISSUE TITLE
FREB: Get the stack trace data into Kusto

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#197]
We need the problem statement in SIA to include the exception type or stacktrace. Lets split this WI into 2 or 3 parts.
1. Get the eventlogs table without any PII
2. Get a part of eventlog like exception type etc
3. Get the full stacktrace in encrypted form

**Comment by andreyse** [comment]
Currently ETW event is back in Kusto and provides information that event has been raised for the "site" and provides source such as : <Provider Name="ASP.NET 4.0.30319.0"/> or <Provider Name=".NET Runtime"/>

**Comment by andreyse** [comment]
Fix checked in to show an exception type from event logs.
