### ISSUE TITLE
Worker Process Recycle Events should is beeping but not corelating

### ISSUE THREAD

**Issue by aspaan** [ShekharGupta1988/AppLensV2#204]
https://applensv2.azurewebsites.net/sites/ilivingapp/detectors/workerprocessrecycle?startTime=2016-12-20

**Comment by ShekharGupta1988** [comment]
The reason for that is "worker process restart" is a umbrella detector. 
We only correlate umbrella detectors when no high priority detectors gets correlated to reduce noise and redundancy.

In this case, If you notice, user did a site restart. So User Initiated site restart detector got correlated. Now this activity would cause worker process restart as well. But it doesn't make sense to correlate that as its a result of user restarting the site.

**Comment by ShekharGupta1988** [comment]
@aspaan - feel free to close the issue if this is convincing. Otherwise, we can discuss in person.

**Comment by andreyse** [comment]
Shekhar you are right - it is by design from beginning
