### ISSUE TITLE
Webjob count incorrect for few sites

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#211]
https://applensv2.azurewebsites.net/sites/soukcom/detectors/cpuanalysis?startTime=2016-12-26T17:25:32.357Z
https://applensv2.azurewebsites.net/sites/elevatewebjobsreportgenerationzipanddeletedev/appanalysis

**Comment by ShekharGupta1988** [comment]
One easy fix - we can list down web job names using vfs api in scm.

**Comment by hforeste** [comment]
Just curious. How were we fetching web job count before? Also don't we need customer credentials to make a vfs call?

**Comment by ShekharGupta1988** [comment]
closing for now.  The count is fetched from analytics cluster
We need to think about AppLens for WebJobs as a separate bigger work item.
