### ISSUE TITLE
ExecuteRemoteSubQuery failure : Value does not fall within the expected range

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#218]
Two of the kusto calls in PROD failed with following error at the same time:

System.Exception: Failed to Execute Kusto Query. Kusto ClientRequestId : ac84aff6-af02-434e-bb7f-eefa960956a9, Exception : [0]Kusto.Cloud.Platform.Utils.UtilsException: [UtilsException] Query execution has resulted in error (80131501): Partial query failure: 0x80131501 (message: 'ExecuteRemoteSubQuery failure: ', details: 'CLR exception: System.ServiceModel.FaultException`1[Kusto.Cloud.Platform.Communication.PlatformExceptionDetail]: Value does not fall within the expected range. (Fault Detail is equal to Value does not fall within the expected range.
System.ArgumentException: Value does not fall within the expected range.

**Kusto Requests Information:**

Timestamp=2017-01-04T08:05:59.3528211Z
ClientRequestId=ac84aff6-af02-434e-bb7f-eefa960956a9
ActivityId=69ccd375-7c9d-4f07-9eec-97604d792498
ActivityType=PO-OWIN-CallContext
MachineName=RD0003FF2449D0
ProcessName=Kusto.Azure.Svc
ProcessId=10780
ThreadId=3404
AppDomainName=RdRuntime
ActivityStack=(Activity stack: CRID=ac84aff6-af02-434e-bb7f-eefa960956a9 ARID=69ccd375-7c9d-4f07-9eec-97604d792498 > PO-OWIN-CallContext/69ccd375-7c9d-4f07-9eec-97604d792498)
MonitoredActivityContext=ActivityType=PO-OWIN-CallContext, Timestamp=2017-01-04T08:05:59.0403158Z, ParentActivityId=69ccd375-7c9d-4f07-9eec-97604d792498, TimeSinceStarted=312.5053 [ms]

Timestamp=2017-01-04T08:05:59.2138718Z
ClientRequestId=aab848b9-3b44-4275-b4c2-702cd2443654
ActivityId=41709ec1-c090-477d-90d0-d014153780be
ActivityType=PO-OWIN-CallContext
MachineName=RD0003FF24996D
ProcessName=Kusto.Azure.Svc
ProcessId=2884
ThreadId=10948
AppDomainName=RdRuntime
ActivityStack=(Activity stack: CRID=aab848b9-3b44-4275-b4c2-702cd2443654 ARID=41709ec1-c090-477d-90d0-d014153780be > PO-OWIN-CallContext/41709ec1-c090-477d-90d0-d014153780be)
MonitoredActivityContext=ActivityType=PO-OWIN-CallContext, Timestamp=2017-01-04T08:05:58.9013437Z, ParentActivityId=41709ec1-c090-477d-90d0-d014153780be, TimeSinceStarted=312.5281 [ms]

**Comment by hforeste** [comment]
Hey Shekhar, can you paste the kusto query that you found for this?

**Comment by ShekharGupta1988** [comment]
hi Hawk, the kusto query in 1 request was getTenantId and other request was to GetRuntimeAvailability

**Comment by ShekharGupta1988** [comment]
Not able to repro this. closing this for now. will reopen this if we saw more instances of this issue in PROD.
