### ISSUE TITLE
PROD : PerfCounter Detector Error - Resource Group Not Found

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#236]
PROD Request Ids for which failures were encountered:
g-7180c2fb-f6fb-47c6-9266-ee547ea25933
g-70dd0494-89d4-40df-9239-489f78565307

it looks like the two failures happened in “AppDomainsUnloaded” and “Garbagecollectiongen2”.

Error seems to indicate that Resource Group was not found in geomaster

**Comment by ShekharGupta1988** [comment]
Site Name : thor-api

**Comment by stevenernst131** [comment]
The errors in those two requests say that resource group cannot be found:

"Code":"NotFound","Message":"Cannot find ResourceGroup with name jetdev-appsvc.","Target":null,"Details":[{"Message":"Cannot find ResourceGroup with name **jetdev-appsvc**."}

'https://geomaster.azurewebsites.windows.net:444/subscriptions/**cc8284d9-680c-466e-a439-7782f045af39**/resourceGroups/**jetdev-appsvc**/providers/Microsoft.Web/sites/thor-api/perfcounters

However there are 3 [thor-api sites,](https://wawsobserver.azurewebsites.net/Sites/thor-api) all on different stamps and subscriptions. In this care the subscription did not match the correct resource group/stamp (As far as I can tell for these sites the name of the resource group is the same as the name of the mini stamp)

@hforeste do you think this could be an observer issue?

**Comment by hforeste** [comment]
As discussed in person, just so also anyone else who views this issue would know. I need to first fix the issue on [AppLensV2](https://applensv2.azurewebsites.net/sites/thor-api/appanalysis). I think this will bring us a step closer to figure out how we sent incorrect subscription to geomaster.
