### ISSUE TITLE
PROD : NullRef Exception in CreateKustoQueryUri for Data Source

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#238]
Request Id : g-39ae6de9-3f38-4d17-aaa2-077c866d2f1b

Intermittently,  the call to create kusto uri for tenant Id fails with null ref.
Need to check prod settings to see if we are selecting the right kusto cluster for the stamp requested.

**Comment by hforeste** [comment]
Just another case in which this occurred:

RequestId: g-0e6929bc-8b51-4127-ab55-b95ef9b63fe8

**Comment by ShekharGupta1988** [comment]
This issue is not specific to GetTenantId. It looks like for DataSource, we added a module to create kusto query link. That method is encountering a  null ref.

**Comment by ShekharGupta1988** [comment]
PROD Request Id :
g-71ee7c5a-772d-4aa2-8a66-19b2f4c37953

**Comment by ShekharGupta1988** [comment]
Potential fix In Code-Review
