### ISSUE TITLE
PROD : Pulse Data PRovider giving Unauth

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#241]
While Calling Pulse API, the call received Unauth error:

"Call to pulse api failed. Status Code : Unauthorized, Details : "

This happened for lot of sites.

Some Request Ids:
RequestId
g-ea5e0d6c-069e-431c-be60-b4c3138f55d8
g-f778e0a0-3a33-440e-a6ca-b1ded777b1d0
g-f5b3a323-7fa9-4a19-902a-a2d5c8faa2d8
g-7e1bc699-88c6-43e8-875d-8d2006dad547
g-f2e0161c-08ab-414f-9c69-5b9f4d1ee13c
g-2707ba63-baab-4894-9fca-e79db8019117
g-3aef4dc0-0866-4d15-bfb6-71135112f1b4
g-f21c0739-5ed9-48ce-b1be-6d8b4998a094
g-d4db6d1b-4565-4dd8-a947-97b9b8015fa4
g-ac2cf21a-68eb-41eb-b6be-88e812c4fcc3
g-0a7509d4-ead7-4a8a-b4bb-09aa80da6b08
g-396a2904-0387-487e-89a8-d7a6ee5d4023
g-8e72979d-edfb-4d51-bc24-3537fc9b7d41

**Comment by ShekharGupta1988** [comment]
Issue is understood here. we need to whitelist pulse key

**Comment by stevenernst131** [comment]
Taking responsibility because we will allow PulseAPI to accept multiple keys instead of just one as the quickest solution to this problem
