### ISSUE TITLE
Production Slot not found in SlotMap

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#271]
https://applensv2.azurewebsites.net/sites/goformzsync/detectors/frebanalysis

In the below FREB Detector a KeyNotFoundException is thrown because Production is not found in the map:
![image](https://cloud.githubusercontent.com/assets/7739017/21870852/5edb36b6-d813-11e6-8e03-38b6bd09fb3a.png)

https://wawscus.kusto.windows.net:443/wawsprod?query=H4sIAAAAAAAEAHPJTEzPyy8uyUwOys9JVahRKM9ILUpVCPH0dQ0OcfQNULBTSEksSS3JzE3VMDIwNNc1MNQ1NFQwNLEyMAAiTYXEvBSCqo0MYKph5mcW5%2bWX5JXm5Gi4ViSnFpRk5ue5pJYkZuYUI9TAZUIqC1IVbG0VlLxTK%2f3yS9zyS%2fNS4JJKAFFY7y3CAAAA

DiagnosticRole | where TIMESTAMP > datetime(2017-01-11 14:00:00) and TIMESTAMP > datetime(2017-01-11 20:00:00) | where isnotnull(ExceptionDetails) | where ExceptionType == "KeyNotFoundException"

**Comment by stevenernst131** [comment]
What did we do to close this?

**Comment by aspaan** [comment]
changes made to observer and deployed
