### ISSUE TITLE
Sia : Downtime Events sometimes not sorted according to rank

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#273]
Ex: https://applensv2.azurewebsites.net/sites/fuxion/appanalysis?startTime=2016-12-14
Look at last downtime period in this url.
CPU should have been above FREB as it has a higher rank than FREB. However, it was placed below FREB in api response.

The issue is understood and fix is in progress.

**Comment by stevenernst131** [comment]
Is this a bug in the UI?

**Comment by ShekharGupta1988** [comment]
send a CR
