### ISSUE TITLE
Auto Scale Detector

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#290]
https://wawscus.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
AntaresAdminSubscriptionAuditEvents
| where (TIMESTAMP >= datetime(2017-01-06T23:30:00Z) and TIMESTAMP < datetime(2017-01-08T22:15:00Z))
| where Tenant == 'd45b9fbd638a4ae8b0b56f5774bb3ac1'
| order by TIMESTAMP asc
| where (SubscriptionId=='9fe1ec35-0f0d-4c21-ae2b-3688aa6879fc') or (SiteName=='goformzsync')

Shows the rules:
https://azureinsights.kusto.windows.net:443/Insights [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
JobTraces | where (TIMESTAMP >= datetime(2017-01-08T17:45:00Z) and TIMESTAMP < datetime(2017-01-08T19:15:00Z)) |  order by TIMESTAMP asc 
|  where jobPartition=="9fe1ec35-0f0d-4c21-ae2b-3688aa6879fc" 
| where operationName == "GetAutoscaleProfile" 
| parse message with * "Profile: '" Profile "'" * 
| where message contains "serverfarms/goformz" 
| summarize count() by Profile 
| project Profile 

Current site: https://applensv2.azurewebsites.net/sites/goformzsync/detectors/instanceallocations?startTime=2017-01-07T23:00&endTime=2017-01-08T23:00

**Comment by hforeste** [comment]
@stevenernst131  is this still needed?
