### ISSUE TITLE
Create detector for external n/w dependency slowness

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#293]

**Comment by hforeste** [comment]
We had a case where a customer was complaining about their site latency. The customers application consisted of a web app and SQL Azure db. 

The customer scaled the web app to P2 but that only helped a little bit. Their web app had occasional 1 sec calls. 

Turns out that SQL Azure had some issues where if audit logging is enabled it impacted response time. 

Create a detector that tracks external dependency slowness

**Comment by PraveenTB** [comment]
Another example where this should have helped.

https://applensv2.azurewebsites.net/sites/rtfunctionseventsaggregatorsvc-bay/detectors/frebanalysis?startTime=2017-02-10T00:22:00.000Z&endTime=2017-02-11T00:22:00.000Z

Kusto Query:
RecommendationEvents
| where SourceMoniker =~ "WAWSPRODBAY057"
| where TIMESTAMP > ago(30d)
| where EventId == 64113
| where SymptomName == "SlowResponse" 
| where SiteName =~ "rtfunctionseventsaggregatorsvc-bay" 
| project PreciseTimeStamp, RoleInstance, EventId, SymptomName, EventMessage, Message , SiteName, SymptomValueName, SymptomValue, SymptomValueUnit, AdditionalInfo 
| top 5000 by PreciseTimeStamp asc 
| summarize count(), avg(SymptomValue)  by bin(PreciseTimeStamp, 1d) | order by PreciseTimeStamp asc | render barchart
