### ISSUE TITLE
Slot Runtime SiteName Map seems to be incorrect

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#298]
http://applensv2.azurewebsites.net/sites/atlasapiprod/detectors/frebanalysis?startTime=2017-1-04

The freb detector finds numerous freb logs but they are all from runtime sitename atlasapiprod and not the other runtime sitename "atlasapiprod__41db" even though based on the availability pattern, it looks like the freb logs actually belong to the main site. There was also no other detectors that beeped for that downtime. 

Freb Query:
AntaresWebWorkerFREBLogs
| where PreciseTimeStamp >= datetime(2017-01-04 00:00:00) and PreciseTimeStamp <= datetime(2017-01-05 00:00:00) and Tenant =~ "c44ae227c52b497a86f1e653006d0f21"
| where SiteName in ("atlasapiprod__41db","atlasapiprod") and StatusCode >= 500
| project PreciseTimeStamp , SiteName, StatusCode , HttpSubStatus
| summarize count() by SiteName, StatusCode , HttpSubStatus, bin(PreciseTimeStamp, 5m)

**Comment by ShekharGupta1988** [comment]
CRSHost
wwm-contactus-demo
us-engage-build-west
prd-ipp-api
inspirehubcom-west
goapp-app-west
api-drivepractice
erp1
realforsikring
AshurstCDE
cla-entitlements-portal
softwarerepo
PFClientWebPortal
fctd
pfllink
ttspoc-go2
cla-entitlements-api
u4-receipt-ocrmessaging0
ConnectedCRM
prensagnf
u4-receipt-classification
u4-receipt-ocrmessaging1
