### ISSUE TITLE
Requests dropped detector should expose reason for requests dropped because of "The connection with the server has been terminated"

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#313]
Consider to look at win32 status code : 12030 

Examples: 

https://applensv2.azurewebsites.net/sites/wprodpod21-dx1dnn1/appanalysis?startTime=2017-1-27

Adjusted query for dropped requests: (sorry it is too big for this example)

AntaresIISLogFrontEndTable
| where PreciseTimeStamp >= datetime(2017-01-27 04:35:00) and PreciseTimeStamp <= datetime(2017-01-27 05:35:00) and Tenant =~ "7a992bc755e44518b9269429e28b9e08"
| where Cs_host =~ "wprodpod21-dx1dnn1.azurewebsites.net" or Cs_host endswith ".wprodpod21-dx1dnn1.dx1app.com" or Cs_host =~ "wprodpod21-dx1dnn1.dx1app.com" or Cs_host endswith ".hi-techmotorsports.com" or Cs_host =~ "hi-techmotorsports.com" or Cs_host endswith ".pcpmotorsports.com" or Cs_host =~ "pcpmotorsports.com" or Cs_host endswith ".honda4u.com" or Cs_host =~ "honda4u.com" or Cs_host =~ "southbayperformancecenter.com" or Cs_host endswith ".southbayperformancecenter.com" or Cs_host =~ "hollisterpowersports.com" or Cs_host endswith ".hollisterpowersports.com" or Cs_host =~ "gridleyhonda.com" or Cs_host endswith ".gridleyhonda.com" or Cs_host =~ "teamecc.com" or Cs_host endswith ".teamecc.com" or Cs_host =~ "adventuremotorsports.net" or Cs_host endswith ".adventuremotorsports.net" or Cs_host =~ "ocharleydavidson.com" or Cs_host endswith ".ocharleydavidson.com" or Cs_host =~ "douglasmotorcycles.com" or Cs_host endswith ".douglasmotorcycles.com" or Cs_host endswith ".snakeriveryamaha.com" or Cs_host =~ "snakeriveryamaha.com" or Cs_host endswith ".lakecitypowersports.com" or Cs_host =~ "lakecitypowersports.com" or Cs_host endswith ".midcitieshonda.com" or Cs_host =~ "midcitieshonda.com" or Cs_host endswith ".northkernmotorsports.com" or Cs_host =~ "northkernmotorsports.com" or Cs_host endswith ".johnburrcycles.com" or Cs_host =~ "johnburrcycles.com" or Cs_host endswith ".tri-countypowersports.com" or Cs_host =~ "tri-countypowersports.com" or Cs_host endswith ".vespaso.com" or Cs_host =~ "vespaso.com" or Cs_host =~ "redrockharley.com" or Cs_host endswith ".redrockharley.com" or Cs_host endswith ".sierramotorsports.com" or Cs_host =~ "sierramotorsports.com" or Cs_host endswith ".akcyclecenter.com" or Cs_host =~ "akcyclecenter.com" or Cs_host endswith ".fivevalleyhondayamaha.com" or Cs_host =~ "fivevalleyhondayamaha.com" or Cs_host endswith ".powersportsnorthwest.com" or Cs_host =~ "powersportsnorthwest.com" or Cs_host endswith ".skwatercraftrentals.com" or Cs_host =~ "skwatercraftrentals.com" or Cs_host endswith ".carlscycle.com" or Cs_host =~ "carlscycle.com" or Cs_host endswith ".cliffscyclecenter.com" or Cs_host =~ "cliffscyclecenter.com" or Cs_host endswith ".coronamotorsports.com" or Cs_host =~ "coronamotorsports.com" or Cs_host endswith ".coynepowersports.com" or Cs_host =~ "coynepowersports.com" or Cs_host endswith ".hondaofhammondla.com" or Cs_host =~ "hondaofhammondla.com" or Cs_host endswith ".langstonmotorsports.com" or Cs_host =~ "langstonmotorsports.com" or Cs_host endswith ".motosportsofukiah.com" or Cs_host =~ "motosportsofukiah.com" or Cs_host endswith ".polarisofportland.com" or Cs_host =~ "polarisofportland.com" or Cs_host endswith ".ronanpowerproducts.com" or Cs_host =~ "ronanpowerproducts.com" or Cs_host endswith ".salinasmc.com" or Cs_host =~ "salinasmc.com" or Cs_host endswith ".shivelyhardware.com" or Cs_host =~ "shivelyhardware.com" or Cs_host endswith ".sierrasportmarine.com" or Cs_host =~ "sierrasportmarine.com" or Cs_host endswith ".sknorthwest.com" or Cs_host =~ "sknorthwest.com" or Cs_host endswith ".bellevuemotosports.com" or Cs_host =~ "bellevuemotosports.com" or Cs_host endswith ".landnseamarine.com" or Cs_host =~ "landnseamarine.com" or Cs_host endswith ".ridemotorsports.com" or Cs_host =~ "ridemotorsports.com" or Cs_host endswith ".pacificyamaha.com" or Cs_host =~ "pacificyamaha.com" or Cs_host endswith ".victorymotorcyclesch.com" or Cs_host =~ "victorymotorcyclesch.com" or Cs_host endswith ".irvseaverbmw.com" or Cs_host =~ "irvseaverbmw.com" or Cs_host endswith ".jetworldpowersports.com" or Cs_host =~ "jetworldpowersports.com" or Cs_host endswith ".suzukiofvannuys.com" or Cs_host =~ "suzukiofvannuys.com" or Cs_host endswith ".canyonhondamotorcycles.com" or Cs_host =~ "canyonhondamotorcycles.com" or Cs_host endswith ".victorypartsrus.com" or Cs_host =~ "victorypartsrus.com" or Cs_host endswith ".nomearcticcat.com" or Cs_host =~ "nomearcticcat.com" or Cs_host endswith ".cartermotorsports.com" or Cs_host =~ "cartermotorsports.com" or Cs_host endswith ".landnseapowersports.net" or Cs_host =~ "landnseapowersports.net" or Cs_host endswith ".allensalley.net" or Cs_host =~ "allensalley.net" or Cs_host endswith ".kfgracing.com" or Cs_host =~ "kfgracing.com" or Cs_host endswith ".nevadapowerproducts.com" or Cs_host =~ "nevadapowerproducts.com" or Cs_host endswith ".onandoffroadparts.com" or Cs_host =~ "onandoffroadparts.com" or Cs_host endswith ".tnt-motorsports.com" or Cs_host =~ "tnt-motorsports.com" or Cs_host endswith ".kfgmotorsports.com" or Cs_host =~ "kfgmotorsports.com" or Cs_host endswith ".avid-products.com" or Cs_host =~ "avid-products.com" or Cs_host endswith ".hudsonmotorcycles.net" or Cs_host =~ "hudsonmotorcycles.net" or Cs_host endswith ".cycleworksetc.com" or Cs_host =~ "cycleworksetc.com" or Cs_host endswith ".polarispartsrus.com" or Cs_host =~ "polarispartsrus.com" or Cs_host endswith ".yamahaoflasvegas.com" or Cs_host =~ "yamahaoflasvegas.com" or Cs_host endswith ".brownmotorworks.net" or Cs_host =~ "brownmotorworks.net" or Cs_host endswith ".4seasonpowersports.com" or Cs_host =~ "4seasonpowersports.com" or Cs_host endswith ".tacomamotorsports.com" or Cs_host =~ "tacomamotorsports.com" or Cs_host endswith ".hondabikes.com" or Cs_host =~ "hondabikes.com" or Cs_host endswith ".ocktm.com" or Cs_host =~ "ocktm.com" or Cs_host endswith ".apriliaguzziescondido.com" or Cs_host =~ "apriliaguzziescondido.com" or Cs_host endswith ".letsride-idaho.com" or Cs_host =~ "letsride-idaho.com" or Cs_host endswith ".westernhonda.com" or Cs_host =~ "westernhonda.com" or Cs_host endswith ".arlenness-motorcycles.com" or Cs_host =~ "arlenness-motorcycles.com" or Cs_host endswith ".rysonline.com" or Cs_host =~ "rysonline.com" or Cs_host endswith ".azwestallsports.com" or Cs_host =~ "azwestallsports.com" or Cs_host endswith ".papowerequipment.com" or Cs_host =~ "papowerequipment.com" or Cs_host endswith ".ncy-motorsports.com" or Cs_host =~ "ncy-motorsports.com" or Cs_host endswith ".santabarbaramotorsports.com" or Cs_host =~ "santabarbaramotorsports.com" or Cs_host endswith ".florenceyamaha.net" or Cs_host =~ "florenceyamaha.net" or Cs_host endswith ".missionmotorsports.com" or Cs_host =~ "missionmotorsports.com" or Cs_host endswith ".desertthunderindian.com" or Cs_host =~ "desertthunderindian.com" or Cs_host endswith ".pacificmotorsports.biz" or Cs_host =~ "pacificmotorsports.biz" or Cs_host endswith ".indianmotorcycleofauburn.com" or Cs_host =~ "indianmotorcycleofauburn.com" or Cs_host endswith ".mcelectricvehicles.com" or Cs_host =~ "mcelectricvehicles.com" or Cs_host =~ "wfuncenter.com" or Cs_host endswith ".wfuncenter.com" or Cs_host endswith ".onestoppolaris.com" or Cs_host =~ "onestoppolaris.com" or Cs_host endswith ".pacmoto.com" or Cs_host =~ "pacmoto.com" or Cs_host endswith ".roseville-yamaha.com" or Cs_host =~ "roseville-yamaha.com" or Cs_host endswith ".thousandoakspowersports.com" or Cs_host =~ "thousandoakspowersports.com" or Cs_host endswith ".leeshonda.com" or Cs_host =~ "leeshonda.com" or Cs_host endswith ".desertthundermotorsports.com" or Cs_host =~ "desertthundermotorsports.com" or Cs_host endswith ".camda.net" or Cs_host =~ "camda.net" or Cs_host endswith ".pdawy.com" or Cs_host =~ "pdawy.com" or Cs_host endswith ".socalmotorcycles.com" or Cs_host =~ "socalmotorcycles.com" or Cs_host endswith ".ridei90.com" or Cs_host =~ "ridei90.com" or Cs_host endswith ".nationalcouncilmotorcycledealerassociation.com" or Cs_host =~ "nationalcouncilmotorcycledealerassociation.com" or Cs_host endswith ".tetonharley.com" or Cs_host =~ "tetonharley.com" or Cs_host endswith ".oldroadharley.com" or Cs_host =~ "oldroadharley.com" or Cs_host endswith ".pomonavalleyharley-davidson.com" or Cs_host =~ "pomonavalleyharley-davidson.com" or Cs_host endswith ".bmwmcescondido.com" or Cs_host =~ "bmwmcescondido.com" or Cs_host endswith ".hartleymotorsinc.com" or Cs_host =~ "hartleymotorsinc.com" or Cs_host endswith ".motorsportsofolympia.com" or Cs_host =~ "motorsportsofolympia.com" or Cs_host endswith ".californiaharleydavidson.com" or Cs_host =~ "californiaharleydavidson.com" or Cs_host endswith ".dpchd.com" or Cs_host =~ "dpchd.com" or Cs_host endswith ".temeculamotorsports.com" or Cs_host =~ "temeculamotorsports.com" or Cs_host endswith ".i-90motorsports.com" or Cs_host =~ "i-90motorsports.com" or Cs_host endswith ".hbhonda.com" or Cs_host =~ "hbhonda.com" or Cs_host endswith ".captainsmarine.com" or Cs_host =~ "captainsmarine.com" or Cs_host endswith ".socalharleydavidsondealers.com" or Cs_host =~ "socalharleydavidsondealers.com" or Cs_host endswith ".jpmotorsports.com" or Cs_host =~ "jpmotorsports.com" or Cs_host endswith ".zionhd.com" or Cs_host =~ "zionhd.com" or Cs_host endswith ".mtnride.com" or Cs_host =~ "mtnride.com" or Cs_host endswith ".dsharley.com" or Cs_host =~ "dsharley.com" or Cs_host endswith ".desertwindhd.com" or Cs_host =~ "desertwindhd.com" or Cs_host endswith ".hillside-honda.com" or Cs_host =~ "hillside-honda.com" or Cs_host =~ "motoworldelcajon.net" or Cs_host endswith ".motoworldelcajon.net" or Cs_host endswith ".hillsidepowersports.com" or Cs_host =~ "hillsidepowersports.com"
| where User_agent != "AlwaysOn" 
| where Cs_uri_query !contains "DWAS-Handler-Name="
//| where Sc_win32_status == 12030
| order by PreciseTimeStamp asc
| summarize count() by C_ip, Sc_win32_status

**Comment by PraveenTB** [comment]
Request dropped can be due to many reasons and right now all of them are mysteries. "Client went away too soon" is one of the cause, so we should clearly identify the subset of "Requests dropped" that are due to "Client went away too soon". As we understand more reasons for requests getting dropped, we should expose those out too
