### ISSUE TITLE
Create StorageHealth Detector

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#314]
https://applensv2.azurewebsites.net/sites/spvnetquawebsite/appanalysis?startTime=2017-01-26T10:00:00Z

This downtime actually correlates with a sev2 that was going on at that time.
LSI: 30316035 (StorageVolumeHealthWriteFailure), CRI: 30335988

In this case storage volume failover detector should have been marked red and indicated an azure storage issue.

During this downtime, FREB claimed that it was an issue with the application code.

**Comment by ShekharGupta1988** [comment]
I dont think Volume Failover should have correlated here. 
App Downtime (Http5xx) : 10:40 PM - 10:45 PM
Volume Failover Time : 11:30 PM

**Comment by hforeste** [comment]
I think then we may need to rethink the query here or add a different detector that uses StorageVolumeHealth table.

Looking at the StorageVolume health, the volume that the site was on was not healthy during that downtime..

https://jarvis-west.dc.ad.msft.net/ECB8B0B

**Comment by ShekharGupta1988** [comment]
ok..  good point - a new detector probably for storage volume health.
(so that's different than volume failover.)

**Comment by hforeste** [comment]
When storage is intermittent the value is usually 99.0% and higher. eg., 

PreciseTimeStamp	avg_Health
2017-01-26 00:00:00.0000000	100
2017-01-26 00:05:00.0000000	100
2017-01-26 00:10:00.0000000	100
2017-01-26 00:15:00.0000000	100
2017-01-26 00:20:00.0000000	99.6556936513268
2017-01-26 00:25:00.0000000	100
2017-01-26 00:30:00.0000000	100
2017-01-26 00:35:00.0000000	100
2017-01-26 00:40:00.0000000	98.4701765806819
2017-01-26 00:45:00.0000000	100
2017-01-26 00:50:00.0000000	99.8624261552157
2017-01-26 00:55:00.0000000	99.2103142626914
2017-01-26 01:00:00.0000000	100

When storage is down we can beep when volume health is below 98.0%

Following kusto query for detector

AntaresStorageVolumeHealth | where (EventId == 55050 or EventId == 55051) and PreciseTimeStamp >= datetime("2017-01-26 00:00:00") and PreciseTimeStamp <= datetime("2017-01-26 23:59:00")
and VolumeName == "volume-9-default"
| extend Health = iff(Status == "SUCCESS", 1, 0)
| project PreciseTimeStamp , VolumeName , Health
| summarize avg(Health) by bin(PreciseTimeStamp, 5m)
| extend avg_Health = avg_Health * 100.0
| order by PreciseTimeStamp asc

Downtime was at 21:40-21:45

PreciseTimeStamp	avg_Health
2017-01-26 21:40:00.0000000	97.6111960106169
2017-01-26 21:45:00.0000000	97.6982097186701

**Comment by hforeste** [comment]
To get the volume information, Diag role can make call to Observer
