### ISSUE TITLE
Add an API to observer for querying deleted sites

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#332]
If a site is deleted. Observer will return 404. Add an ability to observer that allows users to query for deleted sites and still get relevant data.

**Comment by ShekharGupta1988** [comment]
How will you get hostnames/stamp etc for deleted sites from DB. is there a way?

If its not possible, then an alternative way at applens is to take subId, resource group and hostname as input for deleted sites and directly query API as kusto will have data
