### ISSUE TITLE
Correct hostnames API

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#347]
When querying Observer for LuiIntegrationv1-Prod, the hostnames are coming back with the that sitename in two different ministamps

luiintegrationv1-prod.aseprdcc01.p.azurewebsites.net,luiintegrationv1-prod.aesprdcc01.p.azurewebsites.net

**Comment by PraveenTB** [comment]
Do we understand the issue? It would be nice to know how common this is?
