### ISSUE TITLE
Request for integration of ASE with AppLensv2 to have better access to ASE troubleshooting data & queries

### ISSUE THREAD

**Issue by JatinBavishi** [ShekharGupta1988/AppLensV2#349]
AppServiceEnvironmentName: rtp
ImpactStartTime: 
- Thursday Feb 09 around 15:00 EST (GMT -0500)
- Friday Feb 10 around 07:30 EST (GMT -0500)
ImpactEndTime:
-Wednesday Feb 15th 2pm EST ((GMT -0500)
Feedback: what would you like to see in AppLensV2 to help with this case, provide kusto queries, etc
Case: 117020915296828
Background: Customer tried to scale down the ASE rtp Front End instance count from 4 to 2. They did this twice on Feb 9 & 10. But still see the instance count at 4. So they think scaling is not working & need us to fix this.
Challenges
1.	For FrontEnd and WP activities or events, Primary Portal does not log/Activity log for scaling events.
2.	The existing JSON details might be improved to add operation type instead of simply saying “write operation”
3.	Operations blade within the ASE Overview blade & FE pool blade should show operations events like scaling and others for FE and WP.
4. It was difficult to get the exact kusto queries since the current tooling (Web appTroubleshooter queries did not expose the scaling operations when checking into some of the Admin tables.
5. Also, it is not clear which specific Admin table will contain those details. Hawk Foreste was very kind to provide some details from these tables
AntaresAdminGeoEvents, AntaresAdminSubscriptionAuditEvents, AntaresCloudDeploymentAuditEvents
So it requires jumping through various backend system tables/queries to be able to find all the data.
=============================================
**ASK:** So it will be nice if AppLensv2 can integrate with ASE sites & expose data like how it wonderfully does for sites in public stamps. If applensv2 can expose data on ASE for below operations, it can help resolve these ASE cases faster. 
- ASE Scaling operations (on FE & Worker Pool
- ASE creation/deletion operations.
- Errors during ASE integration with VNET/Gateway/On-Premise Resources etc.
- Any LSI/UD walk impacting ASE site availability.
- Recommendation engine which can compare customer ASE configuration & give feedback if minimum requirements for ASE are not met.

Currently, almost all ASE cases miss FDR since our tooling does not allow faster/easier/intuitive way of looking into the data like applensv2 does.
Thanks
Jatin Bavishi

**Comment by JatinBavishi** [comment]
We resolved the above scaling issue by finding out that one of customer’s other colleagues has set a scale profile ‘rtp-default-prod-rg’  on the FE pool to be a minimum of 4:
So it seems the instance count rolled back to 4 even after customer tried to manually scale down to 2 on FE instance. Our backend queries confirmed on 2/9 going from 4 to 2. But customer portal always showed 4. So it was not possible for them to see an explanation why this happened & they thought scaling is not working for them.

It can help resolve these issues faster if somehow our backend system tooling can check if there are any scaling rule setup which can be overriding such behavior & expose them via applensv2 etc.
Or if portal has additional logic to check any scaling rules existing before customer attempts to make a manual scale change which is in conflict with the rule.

**Comment by hforeste** [comment]
This query shows it clearly that changes are occurring in pairs:
https://wawscus.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.WebExplorer] 
AntaresAdminSubscriptionAuditEvents | where TIMESTAMP >= ago(7d)
| where SubscriptionId == "af58ba63-c0fa-4a75-91e1-3d97cd401cb9" 
| where SourceMoniker == "WAWSPRODSN1" 
| where ResourceGroupName  == "prod-rg"

**Comment by hforeste** [comment]
It seems the heart of this ask is visibility into current deployments (scale, creation, deletion). Surfacing any errors or progress. Did it pass/fail and if fail then why.

I have an issue that address this problem #415
