### ISSUE TITLE
When quota is hit we return 403 and it still show 100% availability

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#35]
We need to consider 403 in the availability chart

**Comment by PraveenTB** [comment]
Noting the tricky part: 

All 403 can't be counted into availability coz they may be coming from either platform (which must be considered as downtime) or app itself returning forbidden due to user auth failure (which must NOT be considered as downtime)

**Comment by andreyse** [comment]
Looks like we can close it as won't fix
