### ISSUE TITLE
Cache detector data (metrics, abnormalities, etc.,) from appAnalysis call

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#354]
ProblemDescription: When we make an appAnalysis call from AppLensV2 we get all the data for correlating and issue detected detectors. When we click on those detectors to view their individual data, we make another GetDetectorResource call to the GeoRegion.

**Comment by PraveenTB** [comment]
This is a good optimization however given the data is already cached in Kusto rest API , a new cache's improvement is fairly limited

**Comment by PraveenTB** [comment]
We can do this later. I am moving this out of backlog - lets bring this back when situation changes
