### ISSUE TITLE
expose properties API via geomaster

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#360]

**Comment by PraveenTB** [comment]
Is this for the most used stack type of WI's?

**Comment by ShekharGupta1988** [comment]
https://management.azure.com/subscriptions/{subscription}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/sites/{siteName}/diagnostics/properties?api-version=2015-08-01
