### ISSUE TITLE
No Http traffic shown for app - we can't correlate any downtimes because of that

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#368]
This incident turns out to be App specific issue. 
Memory usage on one of the workers was ~90%. Looking at applens, we found that it was the app process which was consuming most of the memory. Shyam from connectors team restarted the app to mitigate the issue. He is going to follow up with his team to root cause this which possibly looks like a memory leak issue in the app code.
 
https://applensv2.azurewebsites.net/sites/sql-logic-cp-centralus/appanalysis/detectors/memoryanalysis?startTime=2017-02-23T07:45:00.000Z&endTime=2017-02-24T07:45:00.000Z

**Comment by ShekharGupta1988** [comment]
@hforeste - mind taking a look into this. This came as a part of a sev2 CRI from connectors team while I was on-call. I wanted them to use the "Diagnose and Solve" experience from ibiza, however we were not able to fetch any traffic for this site. I checked metering/MDM and there was http traffic on the ASE.

**Comment by PraveenTB** [comment]
Assigning this to hawk
