### ISSUE TITLE
Include FREB into Sia solutions

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#369]
In ibiza, our solutions need to be more accurate like
1. Fix web config
2. Use app insights
3. Use event logs
4. Transient storage issue - dynamic cache
5. Restart w3wp
6. Andrey may have more here...

**Comment by ShekharGupta1988** [comment]
All the solutions are added by default in sia now. Once detectors starts putting solutions, they will be lighted up automatically
