### ISSUE TITLE
Optimize SC and AppLens UI for "Now" scenario

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#371]
"Observations', "Mitigations" and "Solutions" should be readily visible and must flow one after another.

We need both internal and external UI to look similar or close so that CSS is "in sync" with customer view

**Comment by PraveenTB** [comment]
Feel free to break this into multiple issues if needed

**Comment by ShekharGupta1988** [comment]
Will work on this after finishing #372
