### ISSUE TITLE
Rationalize solutions/mitigations throughout

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#372]
1. Have a master list of solutions
2. Have a way to merge solutions in a non conflicting way
3. Move away from wiki fully
4. Each solution should have its type "quick mitigation" or "troubleshooting" so that UI can display it properly

**Comment by ShekharGupta1988** [comment]
Started working on this.

for 1), we have a master list of solutions but there is missing type field which suggests "Quick solution" or "Deeper Investigation"

for 2), I am still thinking that we can start with merging all solutions and then start resolving the conflicts when they are reported. Probably a UI play to make them sound non-conflicting. Open for thoughts

for 3), You mean solutions in github, right? Wiki should still be there. No?

4) is covered as part of 1)
