### ISSUE TITLE
Check if LocalCache be included in storage volume failover detector

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#38]
Should volume failover detector include local cache path? Right now, Local cache is included as part of latency failover. Need to do 2 things:
- First, check whether local cache can cause downtime and should be considered as volume Failover
- If yes, maybe its a good idea to separate local cache calls in a separate metric instead of putting it in latency failover metric

**Comment by aspaan** [comment]
confirmed with kranthi local cache does not cause down time. added them to metrics but not in abnormal time periods
