### ISSUE TITLE
ASE : MultiRole OR Worker stucked in deployment

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#386]
Issue - When multirole gets stucked in on-start loop for whatever reason, it can cause all sort of issues with ASE ( both control pane and availability. Quite a few CRIs came for this)

The detector needs to:
- Detect the multi-role stuck issue
- Propose solutions to customer like - restart role, reimage role

This is more of "NOW" detector and directly affects IR

**Comment by ShekharGupta1988** [comment]
Maybe we can also include WorkerPool stuck in deployment

**Comment by hforeste** [comment]
@ShekharGupta1988 , can you provide examples here too. For the case where multirole stuck on OnStart. Name of ASE and times.

**Comment by ShekharGupta1988** [comment]
Yes sure. Just search for " MultiRoleNeedsReimage" in sev2 alerts.
Few incidents:
32111999
32142136

**Comment by ShekharGupta1988** [comment]
The controller portion of the multirole can get into a more or less corrupted state where it gets stuck in onstart forever. Solution is to reimage.
