### ISSUE TITLE
MultiRole High CPU/Memory

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#388]
Issue - When multirole gets high CPU due to data role or for whatever reason, it can cause all sort of issues with ASE both control pane and availability.

The detector needs to:
- Detect the multi-role high CPU
- Propose solutions to customer like - restart role, reimage role

this affects both FDR and IR

**Comment by hforeste** [comment]
I can take this one

**Comment by hforeste** [comment]
@ShekharGupta1988  can you provide examples from your servicing loop. Names of ASE and also times
