### ISSUE TITLE
[Freb]: Non detected status code

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#392]
Current site: https://applensv2.azurewebsites.net/sites/witune/appanalysis/detectors/frebanalysis?startTime=2017-02-28T17:19:32.449Z
Please provide feedback here: 
Andrey, for some error code of this site – the label is empty

**Comment by ShekharGupta1988** [comment]
Andrey - this is happening for external facing portal also.

![image](https://cloud.githubusercontent.com/assets/11183841/23591117/49afff40-01a0-11e7-8984-29ecad18e5eb.png)

**Comment by andreyse** [comment]
This is fixed
