### ISSUE TITLE
ASE: Http Error Distribution per worker pool

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#417]
Input : ASE name
Detector : Detects Http error distribution across worker pools in ASE.

**Comment by hforeste** [comment]
Shouldn't the failed HTTP calls in worker surface up in the MultiRoles? What cases are we thinking where this would be valuable?

**Comment by ShekharGupta1988** [comment]
same as Multi-Role. If one worker pool is busted. The errors would be distributed in multi-roles but only one worker is having errors. (this has been occurring few times for sites and has a very clear solution.)
