### ISSUE TITLE
Incorrect sku for site

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#430]
![image](https://cloud.githubusercontent.com/assets/7739017/23720937/16bb6a1e-03f5-11e7-850c-22ec38fd2673.png)

https://wawsobserver.azurewebsites.net/sites/smartglass

![image](https://cloud.githubusercontent.com/assets/7739017/23720956/20ee2328-03f5-11e7-9b9a-2c146cb6ee61.png)

**Comment by ShekharGupta1988** [comment]
I think the problem is we are also using Analytics pipeline which is overwritting the sku from observer.
Tht data source is not very reliable.

**Comment by hforeste** [comment]
Is this still relevant?
