### ISSUE TITLE
Storage Health beeping when storage health was 100%

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#436]
https://applensv2.azurewebsites.net/sites/support-bay-api/appanalysis/detectors/storagehealth

![image](https://cloud.githubusercontent.com/assets/11183841/23767062/07676f64-04bc-11e7-9491-36a217d50654.png)

**Comment by stevenernst131** [comment]
Also it is showing up as orange but I don't see it in any of the downtimes?
