### ISSUE TITLE
ASP.NET Core - Startup errors detection + solutions in support center

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#437]
Startup errors (//build)
Symptoms: Sourabh to send specific errors that indicate startup failures (based on https://docs.microsoft.com/en-us/aspnet/core/publishing/iis#common-errors).   
Action: Sourabh to share any customer assistance information (e.g. your web.config at the point of deployment is malformed, please correct it).

**Comment by PraveenTB** [comment]
Lets make sure solutions is accurate in this detector.
