### ISSUE TITLE
Even though CPU was high, the solution did not contain scale up

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#441]
https://applensv2.azurewebsites.net/sites/slipstreamauto14/appanalysis?startTime=2017-03-07T16:20:00.000Z&endTime=2017-03-07T0:23:20.000Z

**Comment by stevenernst131** [comment]
The CPU detector only provides solutions like that for the right now downtime. We need to add solutions for past downtimes, as in its current state it only says app insights and DaaS

**Comment by stevenernst131** [comment]
This will be satisfied by the recent change to CPU

**Comment by stevenernst131** [comment]
#219
