### ISSUE TITLE
100% down ASE visually looks like 100% healthy

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#443]
Current site: https://applensv2.azurewebsites.net/hostingEnvironments/shgup-ase/detectors/asehealth?startTime=2017-03-09T01:54:39.162Z

if we force set min to 0, we should be fine

**Comment by hforeste** [comment]
@PraveenTB , do you mean the reverse. A 100% healthy ASE looks like its 100% down? Is it because the legend color for HTTP Availability is dark-red?

![image](https://user-images.githubusercontent.com/917998/29530495-e5c0353e-8658-11e7-87c2-add17dfadac6.png)
