### ISSUE TITLE
Formatting of AppLens 

### ISSUE THREAD

**Issue by pker** [ShekharGupta1988/AppLensV2#449]
The suggestions are overwriting the view of recycle events, so it is not possible to check the complete events. Check the point 4 suggestion in the attachment. This is tested on Chrome. 

![image](https://cloud.githubusercontent.com/assets/11184734/23867217/3954c33e-07e9-11e7-8410-669024119659.png)

**Comment by ShekharGupta1988** [comment]
thanks. this is a known bug. See #https://github.com/ShekharGupta1988/AppLensV2/issues/398

**Comment by ShekharGupta1988** [comment]
closing this one. tracked as #398
