### ISSUE TITLE
Use active requests per second as another signal along side ase health to determine solutions

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#459]
Suppose Multi Role High CPU detector beeped. We can give a more informed solution if we learned how much requests were coming to through the multi roles.

This [blog](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-configure-an-app-service-environment) mentions hard limits for what P3 multi roles can handle. Given that information we can say something like 

1. "It looks like your multi roles are experiencing high CPU due to the load given. Scale out the number of multi roles"

2. "Your hosting environment is getting 17,000 request per second and your app {sitename} is functioning around 80-85% CPU, please talk to your dev team to scale out your workers."

**Comment by ShekharGupta1988** [comment]
nice. we should also include this blog in solution
