### ISSUE TITLE
Allow analysis on sla and canary sites

### ISSUE THREAD

**Issue by fashaikh** [ShekharGupta1988/AppLensV2#481]
`sla-` sites give an error . Site not found in admin api. Havent tested with a canary site, but would be good if that was supported as well.

**Comment by stevenernst131** [comment]
This is an interesting idea but would require a somewhat large change on our part so we would need to figure out exactly how it would work

**Comment by hforeste** [comment]
I have an existing issue opened for deleted resources #332 and #473
