### ISSUE TITLE
Port Exhaustion Detector feedback

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#483]
Goal : we dont want applens or support center to create more CRIs/Support Tickets instead of reducing them 

<See below mail>

It has a very interesting case of Port Exhaustion and Network Dependency call. 
Couple of things that can be done:
- Explicitly call out its App code causing port exhaustion.
- A Good solution for customer to look why network dependency is slow and ports are getting exhausted.

=================================================

From: Ranjith Mukkai Ramachandra 
Sent: Thursday, March 23, 2017 3:04 PM
To: Shekhar Gupta <shgup@microsoft.com>; Aspaan Kamboj <askamboj@microsoft.com>; Praveen Babu Tirumala <Praveen.T@microsoft.com>; Steve Ernst <sterns@microsoft.com>
Subject: RE: Port Exhaustion Feedback in applens

Thanks Shekhar, 

Specifically, one customer I dealt with has an aspnetcore application connecting to SQL database.

He kept complaining about port exhaustion because that’s what we show to him on the portal via the recommendation engine.

But when I looked into the issue, the port exhaustion event was being generated because his app was getting a constant flow of requests while his app was very slow in responding to requests because of his SQL. He had a P1 SQL database   and we saw many LOGIN failures on his sql side.

Once he scaled up the sql database, the port exhaustion events disappeared 

From: Shekhar Gupta 
Sent: Thursday, March 23, 2017 3:01 PM
To: Aspaan Kamboj <askamboj@microsoft.com>; Praveen Babu Tirumala <Praveen.T@microsoft.com>; Steve Ernst <sterns@microsoft.com>
Cc: Ranjith Mukkai Ramachandra <ranjithr@microsoft.com>
Subject: Port Exhaustion Feedback in applens

Hi folks,
Ranjith brought up one more good feedback about Port Exhaustion detector
Just calling it Port Exhaustion seems to indicate that platform has run out of ports as oppose to its customer app slowness or bug causing port to exhaust.
He handled few CRIs last week that were related to Port exhaustions (not necessarily generated to app lens) but the meta point is calling out very specifically that it is your app issue or app slowness. Run profiler etc tools to know why. (to avoid case creation)

Ranjith – if you have anything more to add, please do 😊

Thanks
Shekhar

**Comment by hforeste** [comment]
@ShekharGupta1988 can you add site and time information to this issue so we can take a look at it on applens internal? @aspaan, if network latency detector was public do you think this would of caught it?
