### ISSUE TITLE
Runtime Availability API Performance issue

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#5]
this api is taking right now long time to respond for 24 hrs data : ~5-8 sec on average
Potential fix is to break the call into multiple parallel calls for small time periods and then combine the data.

**Comment by ShekharGupta1988** [comment]
Also think about how to handle the situation when queried for longer duration:
- 7 Days
- 30 Days

**Comment by stevenernst131** [comment]
I checked in a batched call and we will see if it improves perf in production
