### ISSUE TITLE
FREB: Try ELMAH logging for unhandled exceptions 

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#514]
https://docs.microsoft.com/en-us/aspnet/web-forms/overview/older-versions-getting-started/deploying-web-site-projects/logging-error-details-with-elmah-cs

Check if we can advice using it for 500 errors when unhandled exceptions logged in evenglog.xml

**Comment by andreyse** [comment]
http://elmah.github.io/

**Comment by puneetg1983** [comment]
We are suggesting AppInsights so no need for this.
