### ISSUE TITLE
The RequestsDropped Detector Doesn't Use the Right Query for the worker table

### ISSUE THREAD

**Issue by MattTatoczenko** [ShekharGupta1988/AppLensV2#529]
In my time with using the Requests Dropped detector, I've used it to get all requests from the front end and worker. Front End query works fine. Worker query doesn't contain the custom hostname for some sites, so it sometimes doesn't return requests on the worker.

I'll send an email with the specifics, as I don't want to share queries about the customer's sites that I used to find this.

**Comment by ShekharGupta1988** [comment]
assigning it to Aspaan for more investigation.
