### ISSUE TITLE
Fine tune timeout logic for detectors

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#530]
For some reason, even though we throw exception at 30 seconds the overall requests last longer than 30 seconds.

Some RequestIds:
g-cabf3d3c-e305-4357-b35e-8c49f9fc34af
g-5b5221d0-6360-4539-a588-5382e0b89ac7
g-f8c02d1f-f09c-40b8-a111-f2c05a0af076
g-80f5a779-000b-4ff5-9682-f269516eae69

**Comment by stevenernst131** [comment]
This will hopefully be covered by #538 or at least will shed some more light on it

**Comment by stevenernst131** [comment]
Closing- covered by  #538
