### ISSUE TITLE
Support center monitoring dashboard

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#537]
1. Number of tickets we failed to prevent
2.For a particular ticket - customer journey in what he saw, what he did
3. What is customer verbatim
4. What is CSS root cause
5. Raw side errors 
6. Missing solutions
7 Zero observations and Zero solutions occurances

**Comment by ShekharGupta1988** [comment]
Also, need to add :

- Count of cases leaked by every detector

- Count of cases leaked even after trying solution
