### ISSUE TITLE
Proper fix to cancel Detector Tasks after a timeout value

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#538]
Every week there are about 10-20 runtimeavailability calls that timeout due to timeout exception. See if we can reduce them by making optimizations or hacks

**Comment by PraveenTB** [comment]
There are some cases where detector responds sooner but the request takes much longer to finish. Need to investigate the gaps

**Comment by ShekharGupta1988** [comment]
Steve is working on this for all detectors.

**Comment by stevenernst131** [comment]
Hawks comments from an issue which I closed as being a subset of this issue:

For some reason, even though we throw exception at 30 seconds the overall requests last longer than 30 seconds.

Some RequestIds:
g-cabf3d3c-e305-4357-b35e-8c49f9fc34af
g-5b5221d0-6360-4539-a588-5382e0b89ac7
g-f8c02d1f-f09c-40b8-a111-f2c05a0af076
g-80f5a779-000b-4ff5-9682-f269516eae69
