### ISSUE TITLE
Applens UI : Consolidate Connections detector

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#541]
1. Perfmon data from Bilal's event's detector
2. Jenny's systemstat event - TIME_WAIT counts
3. Aspaan's detector
4. Server wide connection
5. Per VM limit of 160 (SNAP Port exhaustion)

**Comment by stevenernst131** [comment]
There are numerous support tickets opened for connection problems and most often the support engineer gets the SystemStat network print out and puts it directly in the email. Example: 
July 14: 

Total = 4055 Inbound = 26, Outbound = 4026, LoopBack = 3 
Established : 4008 
TimeWait : 47 

==> Remote-Endpoint 
==> 13.88.144.00:443 
Established : 3952 
TimeWait : 1 

==> 40.118.250.00:11078 
Established : 1 

==> 100.117.162.00:80 
Established : 2 

==> 13.91.40.00:443 
**Source: https://mssolveweb.partners.extranet.microsoft.com/MSSolveWeb/srdetails.html?q=117071416044438&s=0**

**Comment by stevenernst131** [comment]
Didn't mean to close
