### ISSUE TITLE
Memory Detector - null ref exception 

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#55]
https://applensv2.azurewebsites.net/sites/leadgenwest/detectors/memoryanalysis?startTime=2016-10-24

DiagnosticRole | where PreciseTimeStamp >= ago(1h) and RequestId == "g-ee8991ab-787c-42f1-90f1-aef326759fa8"

**Comment by stevenernst131** [comment]
Fix is in stable for this bug
