### ISSUE TITLE
API SLA : Increase timeout value for runtimeavailability

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#561]
To meet SLO targets for web apps, we need to increase our Pass percentage for Diagnostic APIs.
For that, lets increase the timeout value for runtime availability.

**Comment by ShekharGupta1988** [comment]
Maybe this can be resolved as part of #538

**Comment by stevenernst131** [comment]
Yes I am planning this as part of #538. Top level detectors should have a longer timeout, just to improve our overall API availability.
