### ISSUE TITLE
ArgumentNullException when running Overall Worker CPU Analysis for specific ASE

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#568]
https://applensv2.azurewebsites.net/hostingEnvironments/waws-prod-am2-a470cc26/detectors/workercpuanalysis?startTime=2017-06-10T15:00:00

**Comment by hforeste** [comment]
An error has occurred.","ExceptionMessage":"Value cannot be null.\r\nParameter name: query","ExceptionType":"System.ArgumentNullException","StackTrace":"   at Microsoft.Web.Hosting.Diagnostics.Common.KustoManager.<ExecuteQueryAsync>d__4.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Diagnostics.Common.DataSourceManager.<MakeDependencyCall>d__10`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Web.Hosting.Diagnostics.Common.RoleInstanceHighCPUDetector.<GetMetricDataForMachineOverall>

**Comment by stevenernst131** [comment]
This is a regression that was a result of my most recent CPU/Memory query change. I have sent a code review for a fix
