### ISSUE TITLE
Stamp Level : Database Connectivity Detector 

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#57]
-   SQL pings by controller: Gives Connection Availability for hosting and metering.

AntaresAdminControllerEvents | where TIMESTAMP > datetime(2016-10-20) and TIMESTAMP < datetime(2016-10-21)   and EventId == 40092 | summarize sum(SuccessfulPings), sum(FailedPings ) by SourceMoniker,bin(TIMESTAMP, 5m), ConnectionId
| where SourceMoniker == "WAWSPRODSN1007" 
| where ConnectionId != ""
| extend Availability= todouble(sum_SuccessfulPings) /(sum_SuccessfulPings+sum_FailedPings),StampName=strcat(SourceMoniker,ConnectionId)
| project TIMESTAMP ,StampName , Availability 
| render timechart 
-   SQL Perf counters
  o   Following query lists available counters we can use  (per Database)
  DBStatsFiveMinuteTable | where PreciseTimeStamp >= ago(1d) and SourceMoniker == "WAWSPRODSN1007"  
  | project CounterName, DatabaseName  | summarize count() by CounterName, DatabaseName

**Comment by PraveenTB** [comment]
Request dropped detector and Petr/Lawrence's stamp level dashboard make this work less important
