### ISSUE TITLE
Incorrect data in instance allocation detector for Consumption plan

### ISSUE THREAD

**Issue by karansinghkushwah** [ShekharGupta1988/AppLensV2#596]
ScaleController for consumption plan can go across stamps which might be causing this inconsistency.

Scenario:
https://applensv2.azurewebsites.net/sites/pfgfleuatdataload/appanalysis/detectors/instanceallocations?startTime=2017-06-28T00:54:00.000Z&endTime=2017-06-28T23:54:00.000Z

**Comment by ShekharGupta1988** [comment]
There is a tracking work item for taking care of consumption plan (scale across stamps.)
https://github.com/ShekharGupta1988/AppLensV2/issues/565
