### ISSUE TITLE
CPU Detector break down by site, by process, by webjob

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#60]
When the CPU is high, we need to answer the next level of questions:
1. Which process is culprit?
2. Is this process ours or theirs?
3. Which webapp (multiple app's case) is causing high CPU?
4. Which webjob within the culprit webapp is consuming high CPU.

This is big work item - feel free to break it down. This includes Stamp + GeoR + UI

**Comment by stevenernst131** [comment]
Kranthi is exposing a new table as part of ANT59 that will give cpu and other counters for the worker processes. As a first iteration we will use that. We will be able to look at the CPU of the scm site in order to see web job usage, though we will not get a breakdown by webjob unfortunately
