### ISSUE TITLE
FREB should not report App issue in case canary is down during the abnormal time period.

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#630]
(Issue Reported by bot team - internal customer)

https://applensv2.azurewebsites.net/sites/connector-devportal2-northeurope/appanalysis/detectors/networklatency?startTime=2017-07-16T18:36:58.314Z

![image](https://user-images.githubusercontent.com/11183841/28283923-4a4a4912-6ae4-11e7-9bc9-810b2fc8da63.png)

![image](https://user-images.githubusercontent.com/11183841/28283926-4dfc2a44-6ae4-11e7-8522-da2e81617055.png)

**Comment by andreyse** [comment]
CheckContainerHealth  is the method to use here
