### ISSUE TITLE
Advise Application Insights based on stack

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#637]
Andrey – can you open an issue to track this if there is not?

From: Steve Ernst 
Sent: Wednesday, July 19, 2017 8:46 AM
To: Andrey Severtokov <andreyse@microsoft.com>; Shekhar Gupta <shgup@microsoft.com>; Aspaan Kamboj <askamboj@microsoft.com>
Subject: RE: Incorrect solutions per stack

This is a good catch. We should discuss so that every single detector doesn’t have to worry about filtering based on stack. 

Thanks,

Steve

From: Andrey Severtokov 
Sent: Tuesday, July 18, 2017 6:46 PM
To: Shekhar Gupta <shgup@microsoft.com>; Aspaan Kamboj <askamboj@microsoft.com>; Steve Ernst <sterns@microsoft.com>
Subject: RE: Incorrect solutions per stack

This is not coming from Freb.

There are 4 cases where this solution provided and stack was PHP or Java 

CPU and Memory detectors also have solution for app insights. We should probably check for stack for them as well.

There are bunch of other detectors that use app insights as well. 

Let’s sync up tomorrow and talk about making SiteProperties task called once and reuse it in detectors that need to determine stack 

https://appsvcux.kusto.windows.net:443/APPSvcUX [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
ClientTelemetry | where TIMESTAMP >= ago(1d) and source =~ "SupportCenter"
| where action contains "SolutionTried"
| parse ['data'] with * "appStack=" appStack  ';' *
| parse ['data'] with * "solution=" solution  ';' *
| where solution == "Enable and Check Application Insights Logs." and (appStack == "PHP" or appStack == "Java")

https://applensv2.azurewebsites.net/sites/bizbruneiweb/appanalysis?startTime=2017-07-17T21:38:00.000Z&endTime=2017-07-18T21:38:00.000Z

Shekhar, for this particular case https://applensv2.azurewebsites.net/sites/osmoaxelta/appanalysis?startTime=2017-07-17T21:38:00.000Z&endTime=2017-07-18T21:38:00.000Z

I see first abnormal period is 1:45 pm – 1:55 pm – and no Application Insights mentioned , then looking in this session https://applensv2.azurewebsites.net/sites/osmoaxelta/supportcentersessions/18116fc2-d7df-4c4e-a7ed-54cdc780dba2?startTime=2017-07-17T21:38:00.000Z&endTime=2017-07-18T21:38:00.000Z

And there down time summary shows 1:40-1:45 and App Insights as a solution. Can you give some details why it shows different downtimes that customer sees and app analysis shows? And different solutions. 

For this case https://applensv2.azurewebsites.net/sites/enex-co/appanalysis?startTime=2017-07-17T21:38:00.000Z&endTime=2017-07-18T21:38:00.000Z same thing App insights mentioned in support center session but no in appanalysis

From: Shekhar Gupta 
Sent: Tuesday, July 18, 2017 2:57 PM
To: Aspaan Kamboj <askamboj@microsoft.com>; Andrey Severtokov <andreyse@microsoft.com>
Cc: Steve Ernst <sterns@microsoft.com>
Subject: RE: Incorrect solutions per stack

Andrey – can you check?
Andrey – can you check if FREB is still giving App Insights for PHP App?

https://appsvcux.kusto.windows.net:443/APPSvcUX [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
ClientTelemetry | where TIMESTAMP >= ago(1d) and source =~ "SupportCenter"
| where action contains "SolutionTried"
| parse ['data'] with * "appStack=" appStack  ';' *
| parse ['data'] with * "solution=" solution  ';' *
| where solution != ""
| summarize SolutionsTried = makeset(solution) by appStack
		
	appStack	SolutionsTried
	Unknown Stack	[
  "Restart your app"
]
	PHP	[
  "Turn on PHP Logging",
  "Restart your app",
  "Enable and Check Application Insights Logs.",
  "Scale Up App Service Plan"
]
	Node	[
  "Restart your app"
]
	Java	[
  "Enable and Check Application Insights Logs.",
  "Scale Up App Service Plan",
  "Restart your app"
]
	ASP.Net Core	[
  "Enable and Check Application Insights Logs.",
  "Restart your app",
  "Scale Up App Service Plan"
]
	ASP.Net	[
  "Open Application Event Logs",
  "Restart your app",
  "Enable and Check Application Insights Logs.",
  "Scale Up App Service Plan",
  "Restart site process on specific instance(s)"
]
		[
  "Enable and Check Application Insights Logs.",
  "Restart your app",
  "Open Application Event Logs"
]

-Shekhar
From: Shekhar Gupta 
Sent: Tuesday, June 27, 2017 11:09 AM
To: Aspaan Kamboj <askamboj@microsoft.com>; Andrey Severtokov <andreyse@microsoft.com>
Cc: Steve Ernst <sterns@microsoft.com>
Subject: Incorrect solutions per stack

Below is the query that summarizes the solutions customers have tried for different stack.
Based on the stack, there are some incorrect solutions that we are suggesting. (logged #558)

Andrey/Aspaan – I have assigned the issue to you for now. Most likely FREB and Log Analyzer needs to be updated.

https://appsvcux.kusto.windows.net:443/APPSvcUX [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
// Solutions Tried Per Stack
ClientTelemetry | where TIMESTAMP >= ago(2d) and source =~ "SupportCenter"
| where action contains "SolutionTried"
| parse ['data'] with * "appStack=" appStack  ';' *
| parse ['data'] with * "solution=" solution  ';' *
| where solution != ""
| summarize SolutionsTried = makeset(solution) by appStack

		
	appStack	SolutionsTried
	Unknown Stack	[
  "Restart your app",
  "Enable and Check Application Insights Logs.",
  "Open Application Event Logs",
  "Scale Up App Service Plan",
  "Restart site process on specific instance(s)"
]
	PHP	[
  "Turn on PHP Logging",
  "Open Application Event Logs",
  "Enable and Check Application Insights Logs.",
  "Restart your app"
]
	Orchard	[
  "Restart your app"
]
	Node	[
  "Enable and Check Application Insights Logs.",
  "Restart your app"
]
	Java	[
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs."
]
	ASP.Net Core	[
  "Restart your app",
  "Enable and Check Application Insights Logs."
]
	ASP.Net	[
  "Open Application Event Logs",
  "Scale Up App Service Plan",
  "Restart your app",
  "Enable and Check Application Insights Logs.",
  "Revert Deployment",
  "Restart site process on specific instance(s)",
  "Remote profile your web app.",
  "Get Memory Dump of Process and analyze it."
]
		[
  "Open Application Event Logs",
  "Restart your app",
  "Enable and Check Application Insights Logs.",
  "Check your Web.config",
  "Get Memory Dump of Process and analyze it.",
  "Scale Up App Service Plan",
  "Restart site process on specific instance(s)"
]

This Query summarizes the solutions we presented to customer per stack:

https://appsvcux.kusto.windows.net:443/APPSvcUX [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
// Solutions Presented Per Stack
ClientTelemetry | where TIMESTAMP >= ago(2d) and source =~ "SupportCenter"
| where action contains "DowntimeVisited"
| parse ['data'] with * "appStack=" appStack  ';' *
| parse ['data'] with * "solutions=" solution  ';' *
| extend solutionsList = split(solution, "|") 
| summarize SolutionsPresented = makeset(solutionsList) by appStack

		
	appStack	SolutionsPresented
	Unknown Stack	[
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs.",
  "Open Application Event Logs",
  "Get Memory Dump of Process and analyze it.",
  "Scale Out App Service Plan",
  "Restart site process on specific instance(s)",
  "Run a Diagnostics as a Service (DaaS) Session"
]
	Python	[
  "Get Memory Dump of Process and analyze it.",
  "Open Application Event Logs",
  "Enable and Check Application Insights Logs."
]
	PHP	[
  "Enable and Check Application Insights Logs.",
  "Turn on PHP Logging",
  "Open Application Event Logs",
  "Explore Local Cache feature for your web app.",
  "Remote profile your web app.",
  "Get Memory Dump of Process and analyze it.",
  "Restart your app",
  "Scale Up App Service Plan"
]
	Orchard	[
  "Open Application Event Logs",
  "Enable and Check Application Insights Logs.",
  "Restart your app",
  "Scale Up App Service Plan"
]
	Node	[
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs.",
  "",
  "Restart site process on specific instance(s)",
  "Remote profile your web app.",
  "Get Memory Dump of Process and analyze it.",
  "Scale Out App Service Plan",
  "Revert Deployment",
  "Run a Diagnostics as a Service (DaaS) Session"
]
	No Traffic	[
  "Revert Deployment",
  "Enable and Check Application Insights Logs."
]
	Java	[
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs."
]
	Classic ASP	[
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs."
]
	ASP.Net Core	[
  "Explore Local Cache feature for your web app.",
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs.",
  "Move Apps into Different App Service Plans",
  "Revert Deployment",
  ""
]
	ASP.Net	[
  "",
  "Get Memory Dump of Process and analyze it.",
  "Open Application Event Logs",
  "Enable and Check Application Insights Logs.",
  "Remote profile your web app.",
  "Scale Up App Service Plan",
  "Move Apps into Different App Service Plans",
  "Restart your app",
  "Scale Out App Service Plan",
  "Run a Diagnostics as a Service (DaaS) Session",
  "Explore Local Cache feature for your web app.",
  "Revert Deployment",
  "Restart site process on specific instance(s)",
  "Check your Web.config"
]
	asp.net	[
  "Open Application Event Logs",
  "Enable and Check Application Insights Logs."
]
		[
  "Restart your app",
  "Scale Up App Service Plan",
  "Enable and Check Application Insights Logs.",
  "Revert Deployment",
  "Open Application Event Logs",
  "Move Apps into Different App Service Plans",
  "Remote profile your web app.",
  "Get Memory Dump of Process and analyze it.",
  "",
  "Run a Diagnostics as a Service (DaaS) Session",
  "Restart site process on specific instance(s)",
  "Check your Web.config",
  "Explore Local Cache feature for your web app.",
  "Scale Out App Service Plan"
]

-Shekhar

**Comment by ShekharGupta1988** [comment]
One way we can solve this problem is to create a solution for "Viewing Application Logs" (based on stack.)

Now, for php, net core apps, this method can return the log file location. For .net app, it can return App insights
