### ISSUE TITLE
Inatance Allocation Events are inaccurate

### ISSUE THREAD

**Issue by kaushalp** [ShekharGupta1988/AppLensV2#648]
I have a scenario where the instance allocation events are not showing the right data. It might be because this is running on a Mega Stamp. 
![applens is inacurate](https://user-images.githubusercontent.com/4186691/28570947-04347dd2-715e-11e7-8a30-7acc8d095a77.png)

In Kusto, I can see that this site is running on multiple stamps at the same time. Will share more details over email.

**Comment by ShekharGupta1988** [comment]
Here is the applens link : 
Applens link: https://applensv2.azurewebsites.net/sites/hs-passapi-azure-live/appanalysis/detectors/instanceallocations?startTime=2017-07-24T00:00:00.000Z&endTime=2017-07-24T23:59:00.000Z

**Comment by aspaan** [comment]
Those missing instance are on different slots

https://applensv2.azurewebsites.net/sites/nirvana-webapi(stage)/appanalysis/detectors/instanceallocations?startTime=2017-07-24
https://applensv2.azurewebsites.net/sites/nirvana-webapi(dev)/appanalysis/detectors/instanceallocations?startTime=2017-07-24
https://applensv2.azurewebsites.net/sites/nirvana-webapi(test)/appanalysis/detectors/instanceallocations?startTime=2017-07-24
