### ISSUE TITLE
{TenantQuery}  not populated

### ISSUE THREAD

**Issue by jsandersrocks** [ShekharGupta1988/AppLensV2#649]
https://applensv2.azurewebsites.net/sites/dundascharthandler-serviceseunanydev/appanalysis/detectors/failedrequestsperuri?startTime=2017-07-25T13:30:33&endTime=2017-07-25T16:28:33

https://wawsneu.kusto.windows.net/wawsprod?query=H4sIAAAAAAAEAH2S20vDMBTG3wX%2fh%2bOeWtilq9TBsIMhigPBy%2bZzSdvjGmmTkZzs5uVvN5ujrutmnpIv%2bX1fTnKGgphCPRqNH%2bT0TklBtyKdsDjH8zPYG5%2bwyFAhPClMuMYJL3BMrJjBIISUEZIVHN%2fr9lper%2bUH0L3sX3p9z3OBibROXZ%2bgrvp%2bUFIfExRM0LNBtfqC4%2fe50VEmNUH4DY3UiJTpJGOKMsvnqFoa1ZwnqNFYp1WK8zZbG4ULjDUn1G2B1Dhu%2fGrRiE1REFyE0BjmC7bSj6J2eqbkOyZUK7EJ90SzYZ5DCOMk0sTI6F8xWC6t6JQqdKDreRCGELjNTUVGcbuFxWGWNkXBFF8jJNIIcnYJFvpbW3MXIF5BzIVTv1RQ%2fB9xupxtRLSL3F%2faxIplE94Yz1%2fs99oqSabS2G5yykkFdDsVW%2ff4X1QQGIC3bY8yxQptPzhEpUpRbR6i1ny2R34ArpAAJfcCAAA%3d

Copy queries and get an error that:  Fix syntax errors by rewriting the query.
AntaresIISLogFrontEndTable
            | where PreciseTimeStamp >= datetime(2017-07-25 13:30:00) and PreciseTimeStamp <= datetime(2017-07-25 16:25:00) and {TenantQuery} 

{TenantQuery} is not filled in

**Comment by ShekharGupta1988** [comment]
This might be a regression with our recent change. Assigning it to @hforeste
