### ISSUE TITLE
Slotruntimemap returns ranges with null values for currentsitename or previous site name

### ISSUE THREAD

**Issue by andreyse** [ShekharGupta1988/AppLensV2#669]
This one causing loosing of some slottime ranges. 

Try this site 

https://localhost:44305/observer/sites/wolverine-api/runtimesiteslotmap

I tested it locally. 

Here is response 

{"Production":[{"RuntimeSitename":null,"StartTime":"2016-07-21T19:43:42","EndTime":"2017-07-21T19:43:42"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-07-21T19:43:42","EndTime":"2017-07-21T19:51:21"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-07-21T19:51:21","EndTime":"2017-08-02T18:44:46"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-08-02T18:44:46","EndTime":"2017-07-19T21:47:33"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-07-19T21:47:33","EndTime":"2017-07-20T18:57:35"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-07-20T18:57:35","EndTime":"2017-08-03T20:56:19.1417028Z"}],"staging":[{"RuntimeSitename":null,"StartTime":"2016-07-21T19:43:43","EndTime":"2017-07-21T19:43:43"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-07-21T19:43:43","EndTime":"2017-07-21T19:51:21"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-07-21T19:51:21","EndTime":"2017-07-19T21:41:22"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-07-19T21:41:22","EndTime":"2017-07-19T21:47:33"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-07-19T21:47:33","EndTime":"2017-08-02T18:44:46"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-08-02T18:44:46","EndTime":"2017-07-20T18:51:07"},{"RuntimeSitename":"wolverine-api__068f","StartTime":"2017-07-20T18:51:07","EndTime":"2017-07-20T18:57:35"},{"RuntimeSitename":"wolverine-api__7a49","StartTime":"2017-07-20T18:57:35","EndTime":"2017-08-03T20:56:19.1417028Z"}],"testing":[{"RuntimeSitename":"wolverine-api__40af","StartTime":"2016-08-02T20:56:19.1417028Z","EndTime":"2017-08-03T20:56:19.1417028Z"}]}

Looks at this code: 

 private Dictionary<string, List<SlotRuntimeSitenameDate>> GetSlotRuntimeSlotMap(IEnumerable<view_WebSites_Audit> webSitesAudits)

**Comment by aspaan** [comment]
I am not able to reproduce this error and saw only one case in the last 30 days
