### ISSUE TITLE
Log a new event for analytics: Sia Success

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#69]
When SIA detects a downtime 
and no detector beeped, it should log a special event A
and few detectors peeped, it should log a special event B

More A's mean that our detector coverage is not complete.
More B's mean we did a good job with detector density

**Comment by ShekharGupta1988** [comment]
Tracking as part of https://github.com/ShekharGupta1988/AppLensV2/issues/19

**Comment by ShekharGupta1988** [comment]
Both issues got closed and we lost track on this one. Reopening this
