### ISSUE TITLE
In case site is not active and customer restarts the app, site restart analysis is not capturing the restart

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#692]
When site is not active and customer restarts the app from portal, its a no-op for site as no site process is active.
However for completeness sake, we should still capture the controller logs and report a restart.

**Comment by stevenernst131** [comment]
We should probably clarify that the site did not actually do a restart however, just to b

**Comment by stevenernst131** [comment]
Didn't mean to close
