### ISSUE TITLE
Update DAAS to collect IIS ETW profiling events

### ISSUE THREAD

**Issue by puneet-gupta** [ShekharGupta1988/AppLensV2#700]
Work on extending DAAS to collect IIS ETW profiling events as a new scenario. This would then be called by Azure Support Center for slowness scenarios

**Comment by PraveenTB** [comment]
Do we need a corresponding UI bug as well. Few things to consider
1. DAAS UI v/s On demand profiling - should there be a difference or consistent?
2. Internal appLens must access the data generated by customer's session. How does the UI look there?
