### ISSUE TITLE
Fix TCP Connections Query

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#725]
Here is the current query:

let ActiveWorkersInTimeRange = toscalar(                                  StatsDWASWorkerProcessTenMinuteTable
| where TIMESTAMP >= datetime(2017-08-22 12:00:00) and TIMESTAMP <= datetime(2017-08-23 12:00:00) and Tenant =~ "175b633ece1f4f4ba4c6bd2dd2082906"
| where (ApplicationPool =~ "smpwfe-prod-wcus" or ApplicationPool startswith "smpwfe-prod-wcus__")
| summarize makeset(RoleInstance));
StatsDWASWorkerProcessTenMinuteTable
| where TIMESTAMP >= datetime(2017-08-22 12:00:00) and TIMESTAMP <= datetime(2017-08-23 12:00:00) and Tenant =~ "175b633ece1f4f4ba4c6bd2dd2082906" and (ApplicationPool =~ "smpwfe-prod-wcus" or ApplicationPool startswith "smpwfe-prod-wcus__")
| project TIMESTAMP, RoleInstance
| join
(
    SystemStats
    | where TIMESTAMP >= datetime(2017-08-22 12:00:00) and TIMESTAMP <= datetime(2017-08-23 12:00:00) and Tenant =~ "175b633ece1f4f4ba4c6bd2dd2082906"
    | where  RoleInstance in (ActiveWorkersInTimeRange)
    | where EventId == 55076
    | extend totalandInbound = split(Details,',' ,0)[0]
    | extend outboundstring = split(Details,',', 1)[0]
    | extend onlyInbound = substring(totalandInbound , indexof(totalandInbound,'Inbound ='))
    | project  TIMESTAMP = bin(TIMESTAMP, 10m), ACTUALTIMESTAMP = TIMESTAMP , RoleInstance, Established = EstablishedConnections, TimeWait , Loopback,  Inbound=toint(replace('Inbound =','', onlyInbound)) ,   Outbound = toint(replace('Outbound = ' , '' , tostring(outboundstring)))
)
on TIMESTAMP, RoleInstance
| project TIMESTAMP, RoleInstance, Established, TimeWait, Loopback, Inbound, Outbound

However this ends up in a jagged view like this:
![image](https://user-images.githubusercontent.com/7739017/29643695-93772c28-8825-11e7-83c1-3c8f2c6db750.png)

You should replace the last 4 lines of the query with this:
| project  TIMESTAMP = bin(TIMESTAMP, 10m), **ACTUALTIMESTAMP = bin(TIMESTAMP ,5m)**, RoleInstance, Established = EstablishedConnections, TimeWait , Loopback,  Inbound=toint(replace('Inbound =','', onlyInbound)) ,   Outbound = toint(replace('Outbound = ' , '' , tostring(outboundstring)))
)
on TIMESTAMP, RoleInstance
| project **TIMESTAMP = ACTUALTIMESTAMP**, RoleInstance, Established, TimeWait, Loopback, Inbound, Outbound

Let me know if you have any questions

**Comment by puneetg1983** [comment]
Thanks @stevenernst131 for the detailed explanation and identifying the issue, I fixed this. I will send a CR shortly. This is how it looks like now

![capture](https://user-images.githubusercontent.com/5299838/29709775-52a005c6-89ab-11e7-8f25-23b3bcfadb43.PNG)
