### ISSUE TITLE
observer api returns staging hostnames when queried for prod site 

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#75]
Invoke "GetHostnames(string sitename)" API for a prod site, the result along with prod hostnames also contains hostnames for the staging slot. 
This is an issue as staging slot traffic also gets added to prod slot and creating false abnormal periods.

**Comment by hforeste** [comment]
This issue is fixed in api-version 2.0
eg., https://support-bay-api.azurewebsites.net/observer/sites/{sitename}/hostnames?api-version=2.0
