### ISSUE TITLE
Invalid Start Time. Start Time cannot be earlier than 30 days

### ISSUE THREAD

**Issue by salmicrosoft** [ShekharGupta1988/AppLensV2#766]
all of my tools on the left side are blank because the first thing that shows up is "Invalid Start Time. Start Time cannot be earlier than 30 days". I don't know where to change my start time

**Comment by ShekharGupta1988** [comment]
There are 2 options to change the start time.
1. In the URL 
2. Go to AppLens home page. You can put the start time there.

**Comment by salmicrosoft** [comment]
Entirely my fault. I was using a URL with timestamp parameters, sorry!

**Comment by ShekharGupta1988** [comment]
no worries. :) let us know for any other issues you face.
