### ISSUE TITLE
Improve existing DAAS Logging

### ISSUE THREAD

**Issue by puneet-gupta** [ShekharGupta1988/AppLensV2#785]
Investigate the existing logging that exists in DAAS and allow the collectors \ analyzers to generate logs of their own that can be used to check what happened or what went wrong

**Comment by puneetg1983** [comment]
1. Enabling Application Logging by going to Website diagnostics (not sure if this is 100% required)
2. Add AppSetting DAAS_DEBUG and set it to TRUE
3. Restart the WebApp
4. Create a new file in D:\home\site\wwwroot\App_Data\Jobs\Continuous\DaaS called DaasRunnger.exe.config and paste the following contents
```
<?xml version="1.0" encoding="utf-8" ?>
	<configuration>
	<system.diagnostics>
	    <trace autoflush="true">
	      <listeners>
	        <add
	        name="TextWriterTraceListener"
	        type="System.Diagnostics.TextWriterTraceListener"
	        initializeData="d:\home\logfiles\Daas.trace.log" />
	      </listeners>
	    </trace>
	  </system.diagnostics>
	  </configuration>

```	
5. Restart DaasRunner once to be sure

Look for the log file present in d:\home\logfiles\Daas.trace.log (there will be one per instance)
