### ISSUE TITLE
Detector: Failures coming only for one instance

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#80]
We should detect that if multiple instances are healthy and only 1 instance is returning failure.

Our suggested solutions in this order:-
1. restart the worker process
2. restart the site from portal
2. scale up and scale down to get to new workers allocated

**Comment by ShekharGupta1988** [comment]
Useful query:

AntaresIISLogWorkerTable 
| where PreciseTimeStamp > ago(1d) and SourceMoniker == "WAWSPRODAM2045" 
|where Cs_host =~ "mystate.azurewebsites.net" or Cs_host endswith ".mystateapi.com" 
| project PreciseTimeStamp, RoleInstance , Http2xx = (Sc_status / 100 == 2), Http3xx = (Sc_status / 100 == 3), Http4xx = (Sc_status / 100 == 4), Http5xx = (Sc_status / 100 == 5)
| summarize count(Http2xx), count(Http3xx), count(Http4xx), count(Http5xx) by bin(PreciseTimeStamp, 5m) , RoleInstance

**Comment by hforeste** [comment]
@aspaan did you already work on this?

**Comment by PraveenTB** [comment]
Other issue covers this
