### ISSUE TITLE
Error loading Instance Allocation Events detector for a specific site

### ISSUE THREAD

**Issue by linitram** [ShekharGupta1988/AppLensV2#816]
https://applensv2.azurewebsites.net/sites/buggy-bits/appanalysis/detectors/instanceallocations?startTime=2017-10-13T16:00:00.000Z&endTime=2017-10-13T20:54:00.000Z
![applens_error](https://user-images.githubusercontent.com/20539645/31566635-218b9642-b031-11e7-91a0-427c4c9155d8.png)

**Comment by hforeste** [comment]
Looks like issue is fixed now
