### ISSUE TITLE
New Observer APIs needed for Migration Detectors

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#88]
1. GetServerFarmName (string siteName) 
    Expected output: ResourceGroup\serverfarm_name
   Description : Get server farm name of the website
2.  GetWebsitesInServerFarm(string serverFarm)
   Description : Get all the sites in the server farm
3. GetWebsiteWebspaceName(string siteName)
   Description : Get site's webspace name
4. GetServerFarmWebspaceName(string subId, string serverFarm)
   Description : Get server farm web space name
5. GetWebspaceResourceGroupName(string subId, string webspace)
   Query to get this data:
   select ResourceGroupName from [dbo].[view_WebSpaces] as ws
   inner join [dbo].[view_Subscriptions] as s
   on ws.subscriptionid = s.id
   where s.Name = '<subscription id>'
   and ws.Name = '<webspace name>'
   and s.websystemname = 'WebSites'

**Comment by ShekharGupta1988** [comment]
Talk to Mahatab for more information on the API asks.

**Comment by aspaan** [comment]
2) GetWebsitesInServerFarm(string serverFarm, string subscriptionId)
Description : Get all the sites in the server farm

also will be providing subscriptionid
