### ISSUE TITLE
Log the exception for Kusto Retry attempts

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#881]
Right now, we are not logging exceptions for kusto retry attempts.

**Comment by hforeste** [comment]
Hey @ShekharGupta1988 , we do log exceptions for retry attempts. 

For example:

https://wawsneu.kusto.windows.net:443/wawsprod?query=H4sIAAAAAAAEACXLvQqDMBRA4V3wHS6Z2iEQzY%2bTBaEODoFifYEk3mqgJGCCRejDF%2bx6Ps7dmyXElL0b4xvL4gufFTeEadD9c%2br0A24tmCVearFewYQZ%2bh1DHmZoW1CcseaMGlMyC4KLIRsfEpAR83aQEzuX%2fe7z8Z9ILQSTSgnaoHBUSMeorZSk7mWZstxyVnECZfEDh5hGMJsAAAA%3d

DiagnosticRole
| where TIMESTAMP >= ago(24h) and EventId == 63007 and Message contains "Retry" and ActivityId == "24405664-7e4c-45c0-b165-cfb06b3b3013" 

Are you looking for more than this?

**Comment by ShekharGupta1988** [comment]
ok.. cool.. we are good here.
