### ISSUE TITLE
memory analysis for this site showing negative values 

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppLensV2#890]
https://applensv2.azurewebsites.net/sites/fitwell-prod2/appanalysis/detectors/sitememoryanalysis?startTime=2017-11-23 

![image](https://user-images.githubusercontent.com/11183841/33284646-9efce9ea-d364-11e7-9614-5c436cb82d08.png)

**Comment by stevenernst131** [comment]
This is a PremiumV2 app, and the issue is with the query that gets the instance mapping. This site is in a megastamp where some stamps have all premium sized workers and some regular, the query needs to add a join on Tenant
