### ISSUE TITLE
Storage Health Beeps When No Data

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#939]
![image](https://user-images.githubusercontent.com/7739017/34784096-29f21170-f5e2-11e7-9c4c-9d92808c1c5f.png)

AntaresStorageVolumeHealth
| where PreciseTimeStamp >= datetime(2018-01-09 15:50:00) and PreciseTimeStamp <= datetime(2018-01-10 15:50:00) and Tenant =~ "eedc5bae1b804e369f0558cac13cfe5a"
| where (EventId == 55050 or EventId == 55051)
| where (VolumeName == "volume-0-default" or VolumeName == "volume-0-default-standby" or Details contains "volume-0-default")
| extend Health = iff(Status == "SUCCESS", 1, 0)
| project PreciseTimeStamp , VolumeName , Health
| summarize avg(Health) by bin(PreciseTimeStamp, 5m), VolumeName
| extend avg_Health = avg_Health * 100.0
| order by PreciseTimeStamp asc

that query returns no data

**Comment by ShekharGupta1988** [comment]
https://applensv2.azurewebsites.net/sites/wa-unlockdwebNEU/appanalysis/detectors/storagehealth?startTime=2018-02-19

**Comment by hforeste** [comment]
Current site: https://applensv2.azurewebsites.net/sites/ospdirectoriesapp-prod/appanalysis/detectors/storagehealth?startTime=2018-01-16T02:00:00.000Z&endTime=2018-01-16T04:00:00.000Z
