### ISSUE TITLE
Display overlaps titles and graphs in IE Win10 Anniversary

### ISSUE THREAD

**Issue by jsandersrocks** [ShekharGupta1988/AppLensV2#94]
https://applensv2.azurewebsites.net/sites/nliven/appanalysis
Display is overlapping and unreadable.
![capture20161026160149799](https://cloud.githubusercontent.com/assets/3776974/19743058/b2debcd4-9b95-11e6-949f-10ce6e1ea57c.png)
![capture20161026160227435](https://cloud.githubusercontent.com/assets/3776974/19743057/b2ddf10a-9b95-11e6-941c-55ab2792856c.png)

**Comment by ShekharGupta1988** [comment]
Thanks for reporting. This is a Browser specific issue.
As a workaround, you can use Chrome for now until we fix this issue
