### ISSUE TITLE
ASE Health Check  detector is flagged unnecessarily

### ISSUE THREAD

**Issue by kaushalp** [ShekharGupta1988/AppLensV2#955]
Here is the scenario: https://applensv2.azurewebsites.net/sites/dls2-int.symantec.com/appanalysis/detectors/asehealthcheck?startTime=2018-01-21T23:20:00.000Z&endTime=2018-01-22T04:20:00.000Z

As you can see the ASE Health Check detector is flagged as red even though the query was healthy. There is nothing under additional data or the query results which substantiates this. Looks like a possible bug in the detector.

**Comment by hforeste** [comment]
Issue fixed
