### ISSUE TITLE
TaskCanceledException when IdentifyStampSpecificIncidents

### ISSUE THREAD

**Issue by hforeste** [ShekharGupta1988/AppLensV2#97]
RequestId = g-5c3ff8f2-ce7b-4432-8ff1-a137eb7845c7

**Comment by hforeste** [comment]
There is also an HttpException happening here. 
RequestId = g-28129f95-0fbc-471e-81ee-eb2b9fe7b569

DiagnosticRole | where EventId == 63003 and TIMESTAMP >= ago(7d) and ExceptionType != ""
| summarize count() by ExceptionType, ExceptionDetails

**Comment by stevenernst131** [comment]
This is understood and fix checked in
